"use client";

import { TComponentFormData } from "@/app/_types/manage/manage.types";
import Image from "next/image";
import React, { useState, useEffect, useRef } from "react";

// 카테고리 타입 정의
interface Category {
  id: number;
  name: string;
}

interface SubCategory {
  id: number;
  name: string;
  category_id: number;
}

interface ComponentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (formData: TComponentFormData) => void;
  categories: Category[];
  type: "library" | "object" | "vc_model" | "ns_model" | "etc";
}

const ComponentModal = ({
  isOpen,
  onClose,
  onSubmit,
  categories,
  type,
}: ComponentModalProps) => {
  const [formData, setFormData] = useState<TComponentFormData>({
    thumbnail: null,
    componentName: "",
    version: "0.0.1",
    description: "",
    features: [""],
    environment: "",
    sourceFile: null,
    iconFile: null,
    fbxFile: null,
    categoryId: "",
    subCategoryId: "",
    type: type,
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [iconPreview, setIconPreview] = useState<string | null>(null);
  const [subCategories, setSubCategories] = useState<SubCategory[]>([]);
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<
    string | null
  >(null);

  // 메인 카테고리 변경 시 서브 카테고리 불러오기
  const handleCategoryChange = async (
    e: React.ChangeEvent<HTMLSelectElement>
  ) => {
    const categoryId = e.target.value;
    setFormData((prev) => ({
      ...prev,
      categoryId,
      subCategoryId: "", // 카테고리 변경 시 서브 카테고리 초기화
    }));

    if (categoryId) {
      try {
        const apiUrl =
          process.env.NEXT_PUBLIC_API_URL || "http://localhost:8081";
        const response = await fetch(
          `${apiUrl}/api/categories/subCategories/${categoryId}`
        );
        const result = await response.json();
        if (result.success) {
          setSubCategories(result.data);
        }
      } catch (err) {
        console.error("서브 카테고리 데이터를 불러오는 중 오류 발생:", err);
      }
    } else {
      setSubCategories([]);
    }
  };

  // 컴포넌트가 마운트되거나 categories가 변경될 때 첫 번째 카테고리로 설정
  useEffect(() => {
    if (categories.length > 0) {
      const firstCategoryId = categories[0].id.toString();
      setFormData((prev) => ({
        ...prev,
        categoryId: firstCategoryId,
      }));
      // 첫 번째 카테고리의 서브 카테고리 불러오기
      handleCategoryChange({
        target: { value: firstCategoryId },
      } as React.ChangeEvent<HTMLSelectElement>);
    }
  }, [categories]);

  // 모달이 열릴 때마다 폼 초기화
  useEffect(() => {
    if (isOpen && categories.length > 0) {
      const firstCategoryId = categories[0].id.toString();
      setFormData({
        thumbnail: null,
        componentName: "",
        version: "0.0.1",
        description: "",
        features: [""],
        environment: "",
        sourceFile: null,
        iconFile: null,
        fbxFile: null,
        categoryId: firstCategoryId,
        subCategoryId: "",
        type: type,
      });
      setThumbnailPreview(null);
      setIconPreview(null);
      setAutoGeneratedThumbnail(null);
      setErrors({});
      // 첫 번째 카테고리의 서브 카테고리 불러오기
      handleCategoryChange({
        target: { value: firstCategoryId },
      } as React.ChangeEvent<HTMLSelectElement>);
    }
  }, [isOpen, categories, type]);

  const handleInputChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, files } = e.target;
    if (files && files.length > 0) {
      const file = files[0];
      const ext = file.name.split('.').pop()?.toLowerCase();
      
      if (name === "iconFile") {
        if (!['svg', 'png', 'jpeg', 'jpg'].includes(ext || '')) {
          alert('Icon 파일은 svg, png, jpeg, jpg 확장자만 업로드 가능합니다.');
          e.target.value = '';
          return;
        }
      }

      // VC Model 확장자 체크
      if (formData.type === "vc_model") {
        if (name === "sourceFile" && ext !== "vcmx") {
          alert("VC Model의 소스 파일은 .vcmx 확장자만 가능합니다.");
          e.target.value = "";
          return;
        }
        if (name === "fbxFile" && ext !== "fbx") {
          alert("FBX 파일은 .fbx 확장자만 가능합니다.");
          e.target.value = "";
          return;
        }
      }

      setFormData({
        ...formData,
        [name]: file,
      });

      // 썸네일 이미지인 경우 미리보기 생성
      if (name === "thumbnail") {
        const reader = new FileReader();
        reader.onload = () => {
          setThumbnailPreview(reader.result as string);
          setAutoGeneratedThumbnail(null); // 수동 썸네일 선택 시 자동 생성 썸네일 제거
        };
        reader.readAsDataURL(files[0]);
      }

      // 아이콘 이미지인 경우 미리보기 생성
      if (name === "iconFile") {
        const reader = new FileReader();
        reader.onload = () => {
          setIconPreview(reader.result as string);
        };
        reader.readAsDataURL(files[0]);
      }

      // FBX 파일인 경우 (Model 타입)
      if (name === "fbxFile") {
        setAutoGeneratedThumbnail(null);
        setThumbnailPreview(null);
      }
    
      // 소스 파일이 fbx인 경우 기존 썸네일 제거
      if (name === "sourceFile") {
        setAutoGeneratedThumbnail(null); // 새 파일 선택 시 기존 썸네일 제거
        setThumbnailPreview(null); // 수동 썸네일도 제거
      }
    }
  };

  const handleFeatureChange = (index: number, value: string) => {
    const updatedFeatures = [...formData.features];
    updatedFeatures[index] = value;
    setFormData({
      ...formData,
      features: updatedFeatures,
    });
  };

  const addFeature = () => {
    setFormData({
      ...formData,
      features: [...formData.features, ""],
    });
  };

  const removeFeature = (index: number) => {
    const updatedFeatures = [...formData.features];
    updatedFeatures.splice(index, 1);
    setFormData({
      ...formData,
      features: updatedFeatures,
    });
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    // if (!formData.componentName)
    //   newErrors.componentName = "파일명은 필수입니다.";
    // if (!formData.version) newErrors.version = "버전은 필수입니다.";
    // if (!formData.categoryId) newErrors.categoryId = "카테고리는 필수입니다.";
    // if (!formData.subCategoryId)
    //   newErrors.subCategoryId = "서브 카테고리는 필수입니다.";

    if (!formData.sourceFile) {
      newErrors.sourceFile = "소스/실행 파일은 필수입니다.";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (validateForm()) {
      onSubmit({ ...formData });
      // 폼 초기화 및 미리보기 초기화
      setThumbnailPreview(null);
      setIconPreview(null);
    }
  };

  const removeThumbnail = () => {
    setFormData({
      ...formData,
      thumbnail: null,
    });
    setThumbnailPreview(null);
    setAutoGeneratedThumbnail(null);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center z-50">
      <div className="bg-card rounded-lg p-8 w-[800px] max-h-[90vh] overflow-y-auto relative border border-border shadow-2xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-white text-2xl"
          aria-label="닫기"
        >
          ✕
        </button>

        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label className="block text-white mb-2">타입 선택</label>
            <select
              name="type"
              value={formData.type}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            >
              <option className="bg-gray-800 text-white" value="library">VC PlugIn</option>
              <option className="bg-gray-800 text-white" value="object">NS PlugIn</option>
              <option className="bg-gray-800 text-white" value="vc_model">VC Model</option>
              <option className="bg-gray-800 text-white" value="ns_model">NS Model</option>
              <option className="bg-gray-800 text-white" value="etc">etc</option>
            </select>
          </div>

          <div className="hidden">
            <h3 className="text-white font-semibold mb-4">카테고리 설정</h3>
            <div className="flex gap-4">
              <div className="flex-1">
                <label className="block text-white mb-2">카테고리</label>
                <select
                  name="categoryId"
                  value={formData.categoryId}
                  onChange={handleCategoryChange}
                  className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
                >
                  {categories.map((category) => (
                    <option className="bg-gray-800 text-white" key={category.id} value={category.id.toString()}>
                      {category.name}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex-1">
                <label className="block text-white mb-2">서브 카테고리</label>
                <select
                  name="subCategoryId"
                  value={formData.subCategoryId}
                  onChange={handleInputChange}
                  className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
                  disabled={!formData.categoryId}
                >
                  <option className="bg-gray-800 text-white" value="">서브 카테고리 선택</option>
                  {subCategories.map((subCategory) => (
                    <option
                      className="bg-gray-800 text-white"
                      key={subCategory.id}
                      value={subCategory.id.toString()}
                    >
                      {subCategory.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          <div className="mb-4">
            <label className="block text-white mb-2">파일명</label>
            <input
              type="text"
              name="componentName"
              value={formData.componentName}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            />
            {errors.componentName && (
              <p className="text-red-500 mt-1">{errors.componentName}</p>
            )}
          </div>

          <div className="mb-4">
            <label className="block text-white mb-2">버전</label>
            <input
              type="text"
              name="version"
              value={formData.version}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            />
            {errors.version && (
              <p className="text-red-500 mt-1">{errors.version}</p>
            )}
          </div>


          <div className="mb-4">
            <label className="block text-white mb-2">주요 기능 목록</label>
            {formData.features.map((feature, index) => (
              <div key={index} className="flex mb-2">
                <input
                  type="text"
                  value={feature}
                  onChange={(e) => handleFeatureChange(index, e.target.value)}
                  className="flex-grow bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
                />
                {formData.features.length > 1 && (
                  <button
                    type="button"
                    onClick={() => removeFeature(index)}
                    className="ml-2 bg-red-600 text-white px-3 py-2 rounded"
                  >
                    삭제
                  </button>
                )}
              </div>
            ))}
            <button
              type="button"
              onClick={addFeature}
              className="bg-blue-600 text-white px-3 py-2 rounded mt-2"
            >
              기능 추가
            </button>
          </div>


          {/* 파일 업로드 섹션 */}
          <div className="mb-6 bg-card rounded-xl border border-border p-6 shadow-sm">
            <h3 className="text-white font-semibold mb-4 flex items-center">
              파일 업로드
            </h3>

            {/* 소스/실행 파일 */}
            <div className="mb-4">
              <label className="block text-white mb-2">
                {formData.type === "vc_model" 
                  ? "VCMX 파일 (필수)" 
                  : formData.type === "ns_model" || formData.type === "etc"
                    ? "파일 (필수)" 
                    : "소스/실행 파일 (필수)"}
              </label>
              <input
                type="file"
                name="sourceFile"
                onChange={handleFileChange}
                className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
              />
              {formData.sourceFile && (
                <p className="text-green-500 mt-1">
                  {(formData.sourceFile as File).name} 파일이 선택되었습니다.
                </p>
              )}
              {errors.sourceFile && (
                <p className="text-red-500 mt-1">{errors.sourceFile}</p>
              )}
              <p className="text-gray-400 text-sm mt-2">
                {formData.type === "vc_model" 
                  ? ".vcmx 파일을 업로드해 주세요." 
                  : formData.type === "ns_model" || formData.type === "etc"
                    ? "모든 확장자의 파일을 업로드할 수 있습니다."
                    : "모든 확장자의 파일을 원활하게 업로드할 수 있습니다. (썸네일 미등록 시 기본 썸네일이 제공됩니다)"}
              </p>
            </div>

            {/* FBX 파일 (VC Model 전용) */}
            {formData.type === "vc_model" && (
              <div className="mb-4">
                <label className="block text-white mb-2">
                  FBX 파일 (선택)
                </label>
                <input
                  type="file"
                  name="fbxFile"
                  accept=".fbx"
                  onChange={handleFileChange}
                  className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
                />
                {formData.fbxFile && (
                  <p className="text-green-500 mt-1">
                    {(formData.fbxFile as File).name} 파일이 선택되었습니다.
                  </p>
                )}
                <p className="text-gray-400 text-sm mt-2">
                  FBX 파일을 업로드하면 3D 뷰어 및 자동 썸네일 생성이 지원됩니다.
                </p>
              </div>
            )}

            {/* 아이콘 파일 (VC/NS/etc 모델에서는 제외) */}
            {formData.type !== "vc_model" && formData.type !== "ns_model" && formData.type !== "etc" && (
              <div className="mb-4">
                <label className="block text-white mb-2">
                  Icon 파일 (선택사항)
                </label>
                <div className="relative">
                  <input
                    type="file"
                    name="iconFile"
                    accept=".svg,.png,.jpeg,.jpg"
                    onChange={handleFileChange}
                    className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all pr-12"
                  />
                  {iconPreview && (
                    <div className="absolute right-2 top-1/2 -translate-y-1/2 w-8 h-8 rounded border border-border overflow-hidden bg-card flex items-center justify-center shadow-sm">
                      <img src={iconPreview} alt="아이콘 미리보기" className="w-full h-full object-contain" />
                    </div>
                  )}
                </div>
                {formData.iconFile && (
                  <p className="text-green-500 mt-1">
                    {(formData.iconFile as File).name} 파일이 선택되었습니다.
                  </p>
                )}
              </div>
            )}
          </div>

          {/* 썸네일 설정 섹션 (NS/etc Model은 자동 생성되므로 제외) */}
          {formData.sourceFile && formData.type !== "ns_model" && formData.type !== "etc" && (
            <div className="mb-6 bg-card rounded-xl border border-border mt-4 p-6 shadow-sm">
              <h3 className="text-white font-semibold mb-4 flex items-center">
                썸네일 설정
              </h3>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* 왼쪽: 썸네일 결과 (또는 기본 아이콘) */}
                <div className="flex flex-col items-center justify-center bg-gray-800/50 rounded-xl border border-gray-700 p-6 min-h-[280px]">
                  <div className="relative w-48 h-48 bg-gray-900 rounded-2xl flex flex-col items-center justify-center border border-gray-600 overflow-hidden shadow-inner">
                    {thumbnailPreview || autoGeneratedThumbnail ? (
                      <>
                        <img
                          src={thumbnailPreview || autoGeneratedThumbnail || ""}
                          alt="썸네일"
                          className="w-full h-full object-cover"
                        />
                        <button
                          type="button"
                          onClick={() => {
                            setThumbnailPreview(null);
                            setAutoGeneratedThumbnail(null);
                            setFormData((prev) => ({ ...prev, thumbnail: undefined as any }));
                          }}
                          className="absolute top-2 right-2 bg-red-500/80 text-white rounded-full w-7 h-7 flex items-center justify-center hover:bg-red-500 transition-colors shadow-lg backdrop-blur-sm"
                        >
                          ✕
                        </button>
                      </>
                    ) : (
                      <div className="flex flex-col items-center justify-center opacity-70">
                        <img 
                          src={formData.type === "library" ? "/images/ic-vc.png" : formData.type === "object" ? "/images/ic-ns.png" : "/images/ic-etc.png"} 
                          alt="기본 썸네일" 
                          className="w-12 h-12 mb-4 object-contain opacity-80" 
                        />
                        <span className="text-sm text-gray-400 font-medium tracking-wide">시스템 썸네일 자동 적용</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* 오른쪽: 수동 썸네일 업로드 */}
                <div className="flex flex-col justify-center">
                  <h4 className="text-white font-medium mb-3 text-lg">
                    직접 썸네일 설정 <span className="text-gray-400 text-sm font-normal ml-2">(선택항목)</span>
                  </h4>
                  <p className="text-gray-400 text-sm mb-6 leading-relaxed">
                    직접 이미지를 업로드하지 않으면, 컴포넌트 환경에 맞는 <strong className="text-cyan-400 font-medium">플러그인 아이콘</strong>이 기본 썸네일로 자동 등록됩니다. 별도의 3D 생성과정 없이 빠르고 간편하게 등록이 가능합니다.
                  </p>
                  <label className="text-gray-300 text-sm mb-2 block font-medium">
                    이미지 파일 업로드
                  </label>
                  <input
                    type="file"
                    name="thumbnail"
                    accept="image/*"
                    onChange={handleFileChange}
                    className="w-full bg-gray-900 text-gray-200 p-3 rounded-lg border border-gray-700/50 hover:border-gray-600 focus:ring-1 focus:ring-cyan-500 focus:border-cyan-500 outline-none transition-all text-sm mb-2"
                  />
                  <p className="text-gray-500 text-xs flex items-center gap-1.5">
                    <span className="text-cyan-500">💡</span> 1:1 정방형 비율의 JPG, PNG 확장을 권장합니다.
                  </p>
                </div>
              </div>
            </div>
          )}

          <div className="flex justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2.5 rounded-lg border border-gray-600/50 bg-gray-800/50 text-gray-300 hover:bg-gray-700 hover:text-white transition-all font-medium backdrop-blur-sm"
            >
              취소
            </button>
            <button
              type="submit"
              className="px-6 py-2.5 rounded-lg bg-cyan-600/90 hover:bg-cyan-500 border border-cyan-400/50 text-white font-medium shadow-[0_0_15px_rgba(8,145,178,0.3)] transition-all"
            >
              등록
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ComponentModal;
