"use client";

import { TComponentFormData } from "@/app/_types/manage/manage.types";
import Image from "next/image";
import React, { useState, useEffect, useRef } from "react";
import useUserStore from "@/app/stores/UserStore";
import FbxThumbnailGenerator, { FbxThumbnailGeneratorRef } from "../../_components/common/FbxThumbnailGenerator";
import ThumbnailPlaceholder from "../../_components/common/ThumbnailPlaceholder";

// 카테고리 타입 정의
interface Category {
  id: number;
  name: string;
}

interface SubCategory {
  id: number;
  name: string;
  category_id: number;
}

interface ComponentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (formData: TComponentFormData) => void;
  categories: Category[];
  type: "vc_plugin" | "ns_plugin" | "vc_model" | "ns_model" | "etc";
}

const ComponentModal = ({
  isOpen,
  onClose,
  onSubmit,
  categories,
  type,
}: ComponentModalProps) => {
  const [formData, setFormData] = useState<TComponentFormData>({
    thumbnail: null,
    componentName: "",
    version: "0.0.1",
    description: "",
    features: "",
    environment: "",
    sourceFile: null,
    iconFile: null,
    fbxFile: null,
    categoryId: null as any,
    subCategoryId: null as any,
    type: type,
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [iconPreview, setIconPreview] = useState<string | null>(null);
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<string | null>(null);
  const fbxGenRef = useRef<FbxThumbnailGeneratorRef>(null);
  const [subCategories, setSubCategories] = useState<SubCategory[]>([]);

  // 카테고리 로직 제거됨

  // 모달이 열릴 때마다 폼 초기화
  useEffect(() => {
    if (isOpen) {
      setFormData({
        thumbnail: null,
        componentName: "",
        version: "0.0.1",
        description: "",
        features: "",
        environment: "",
        sourceFile: null,
        iconFile: null,
        fbxFile: null,
        categoryId: null as any,
        subCategoryId: null as any,
        type: type,
      });
      setThumbnailPreview(null);
      setIconPreview(null);
      setAutoGeneratedThumbnail(null);
      setErrors({});
    }
  }, [isOpen, type]);

  const handleInputChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    const { name, value } = e.target;

    // 타입이 변경되는 경우 모든 필드와 파일 초기화
    if (name === "type") {
      setFormData({
        thumbnail: null,
        componentName: "",
        version: "0.0.1",
        description: "",
        features: "",
        environment: "",
        sourceFile: null,
        iconFile: null,
        fbxFile: null,
        categoryId: null as any,
        subCategoryId: null as any,
        type: value as any,
      });
      setThumbnailPreview(null);
      setIconPreview(null);
      setAutoGeneratedThumbnail(null);
      setErrors({});
      return;
    }

    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, files } = e.target;
    if (files && files.length > 0) {
      const file = files[0];
      const ext = file.name.split('.').pop()?.toLowerCase();
      
      if (name === "iconFile") {
        if (!['svg', 'png', 'jpeg', 'jpg'].includes(ext || '')) {
          alert('Icon 파일은 svg, png, jpeg, jpg 확장자만 업로드 가능합니다.');
          e.target.value = '';
          return;
        }
      }

      // VC Model 확장자 체크
      if (formData.type === "vc_model") {
        if (name === "sourceFile" && ext !== "vcmx") {
          alert("VC Model의 소스 파일은 .vcmx 확장자만 가능합니다.");
          e.target.value = "";
          return;
        }
        if (name === "fbxFile" && ext !== "fbx") {
          alert("FBX 파일은 .fbx 확장자만 가능합니다.");
          e.target.value = "";
          return;
        }
      }

      setFormData({
        ...formData,
        [name]: file,
      });

      // 썸네일 이미지인 경우 미리보기 생성
      if (name === "thumbnail") {
        const reader = new FileReader();
        reader.onload = () => {
          setThumbnailPreview(reader.result as string);
          setAutoGeneratedThumbnail(null); // 수동 썸네일 선택 시 자동 생성 썸네일 제거
        };
        reader.readAsDataURL(files[0]);
      }

      // 아이콘 이미지인 경우 미리보기 생성
      if (name === "iconFile") {
        const reader = new FileReader();
        reader.onload = () => {
          setIconPreview(reader.result as string);
        };
        reader.readAsDataURL(files[0]);
      }

      // FBX 파일인 경우 (Model 타입)
      if (name === "fbxFile") {
        setAutoGeneratedThumbnail(null);
        setThumbnailPreview(null);
      }
    
      // 소스 파일이 fbx인 경우 기존 썸네일 제거
      if (name === "sourceFile") {
        setAutoGeneratedThumbnail(null); // 새 파일 선택 시 기존 썸네일 제거
        setThumbnailPreview(null); // 수동 썸네일도 제거
      }
    }
  };

  const handleFeatureChange = (value: string) => {
    setFormData({
      ...formData,
      features: value,
    });
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    // if (!formData.componentName)
    //   newErrors.componentName = "파일명은 필수입니다.";
    // if (!formData.version) newErrors.version = "버전은 필수입니다.";
    // if (!formData.categoryId) newErrors.categoryId = "카테고리는 필수입니다.";
    // if (!formData.subCategoryId)
    //   newErrors.subCategoryId = "서브 카테고리는 필수입니다.";

    if (!formData.sourceFile) {
      newErrors.sourceFile = "소스/실행 파일은 필수입니다.";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (validateForm()) {
      onSubmit({ ...formData });
      // 폼 초기화 및 미리보기 초기화
      setThumbnailPreview(null);
      setIconPreview(null);
    }
  };

  const removeThumbnail = () => {
    setFormData({
      ...formData,
      thumbnail: null,
    });
    setThumbnailPreview(null);
    setAutoGeneratedThumbnail(null);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center z-50">
      <div className="bg-card rounded-lg p-8 w-[800px] max-h-[90vh] overflow-y-auto relative border border-border shadow-2xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-white text-2xl"
          aria-label="닫기"
        >
          ✕
        </button>

        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label className="block text-white mb-2">타입 선택</label>
            <select
              name="type"
              value={formData.type}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            >
              <option className="bg-gray-800 text-white" value="vc_plugin">VC PlugIn</option>
              <option className="bg-gray-800 text-white" value="ns_plugin">NS PlugIn</option>
              <option className="bg-gray-800 text-white" value="vc_model">VC Model</option>
              <option className="bg-gray-800 text-white" value="ns_model">NS Model</option>
              <option className="bg-gray-800 text-white" value="etc">etc</option>
            </select>
          </div>


          <div className="mb-4">
            <label className="block text-white mb-2">파일명</label>
            <input
              type="text"
              name="componentName"
              value={formData.componentName}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            />
            {errors.componentName && (
              <p className="text-red-500 mt-1">{errors.componentName}</p>
            )}
          </div>

          <div className="mb-4">
            <label className="block text-white mb-2">버전</label>
            <input
              type="text"
              name="version"
              value={formData.version}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            />
            {errors.version && (
              <p className="text-red-500 mt-1">{errors.version}</p>
            )}
          </div>


          <div className="mb-4">
            <label className="block text-white mb-2">주요 기능</label>
            <textarea
              value={formData.features}
              onChange={(e) => handleFeatureChange(e.target.value)}
              placeholder="주요 기능을 입력하세요. (줄바꿈 가능)"
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all min-h-[120px] resize-y"
            />
          </div>


          {/* 파일 업로드 섹션 - 타입을 바꿀 때마다 리셋하기 위해 key={formData.type} 추가 */}
          <div key={formData.type} className="mb-6 bg-card rounded-xl border border-border p-6 shadow-sm">
            <h3 className="text-white font-semibold mb-4 flex items-center">
              파일 업로드
            </h3>

            {/* 소스/실행 파일 */}
            <div className="mb-4">
              <label className="block text-white mb-2">
                {formData.type === "vc_model" 
                  ? "VCMX 파일 (필수)" 
                  : formData.type === "ns_model" || formData.type === "etc"
                    ? "파일 (필수)" 
                    : "소스/실행 파일 (필수)"}
              </label>
              <input
                type="file"
                name="sourceFile"
                onChange={handleFileChange}
                className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
              />
              {formData.sourceFile && (
                <p className="text-green-500 mt-1">
                  {(formData.sourceFile as File).name} 파일이 선택되었습니다.
                </p>
              )}
              {errors.sourceFile && (
                <p className="text-red-500 mt-1">{errors.sourceFile}</p>
              )}
              <p className="text-gray-400 text-sm mt-2">
                {formData.type === "vc_model" 
                  ? ".vcmx 파일을 업로드해 주세요." 
                  : formData.type === "ns_model" || formData.type === "etc"
                    ? "모든 확장자의 파일을 업로드할 수 있습니다."
                    : "모든 확장자의 파일을 원활하게 업로드할 수 있습니다. (썸네일 미등록 시 기본 썸네일이 제공됩니다)"}
              </p>
            </div>

            {/* FBX 파일 (VC Model 전용) */}
            {formData.type === "vc_model" && (
              <div className="mb-4">
                <label className="block text-white mb-2">
                  FBX 파일 (선택)
                </label>
                <input
                  type="file"
                  name="fbxFile"
                  accept=".fbx"
                  onChange={handleFileChange}
                  className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
                />
                {formData.fbxFile && (
                  <p className="text-green-500 mt-1">
                    {(formData.fbxFile as File).name} 파일이 선택되었습니다.
                  </p>
                )}
                <p className="text-gray-400 text-sm mt-2">
                  FBX 파일을 업로드하면 3D 뷰어 및 자동 썸네일 생성이 지원됩니다.
                </p>
              </div>
            )}

            {/* 아이콘 파일 (VC/NS/etc 모델에서는 제외) */}
            {formData.type !== "vc_model" && formData.type !== "ns_model" && formData.type !== "etc" && (
              <div className="mb-4">
                <label className="block text-white mb-2">
                  Icon 파일 (선택사항)
                </label>
                <div className="relative">
                  <input
                    type="file"
                    name="iconFile"
                    accept=".svg,.png,.jpeg,.jpg"
                    onChange={handleFileChange}
                    className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all pr-12"
                  />
                  {iconPreview && (
                    <div className="absolute right-2 top-1/2 -translate-y-1/2 w-8 h-8 rounded border border-border overflow-hidden bg-card flex items-center justify-center shadow-sm">
                      <img src={iconPreview} alt="아이콘 미리보기" className="w-full h-full object-contain" />
                    </div>
                  )}
                </div>
                {formData.iconFile && (
                  <p className="text-green-500 mt-1">
                    {(formData.iconFile as File).name} 파일이 선택되었습니다.
                  </p>
                )}
              </div>
            )}
          </div>

          {/* 썸네일 설정 섹션 (NS/etc Model은 자동 생성되므로 제외) */}
          {formData.sourceFile && formData.type !== "ns_model" && formData.type !== "etc" && (
            <div className="mb-6 bg-card rounded-xl border border-border mt-4 p-6 shadow-sm">
              <h3 className="text-white font-semibold mb-4 flex items-center">
                썸네일 설정
              </h3>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* 썸네일 결과 (또는 기본 아이콘 / 3D 뷰어) */}
                <div className="flex flex-col items-center justify-center bg-gray-800/50 rounded-xl border border-gray-700 p-2">
                  <div className="relative w-full aspect-square max-w-[300px] bg-gray-900 rounded-2xl flex flex-col items-center justify-center border border-gray-600 overflow-hidden shadow-inner">
                    {thumbnailPreview ? (
                      <>
                        <img
                          src={thumbnailPreview}
                          alt="썸네일"
                          className="w-full h-full object-cover"
                        />
                        <button
                          type="button"
                          onClick={() => {
                            setThumbnailPreview(null);
                            setFormData((prev) => ({
                              ...prev,
                              thumbnail: undefined as any,
                            }));
                          }}
                          className="absolute top-2 right-2 bg-red-500/80 text-white rounded-full w-7 h-7 flex items-center justify-center hover:bg-red-500 transition-colors shadow-lg backdrop-blur-sm z-30"
                        >
                          ✕
                        </button>
                      </>
                    ) : formData.fbxFile ? (
                      <div className="w-full h-full relative">
                        <FbxThumbnailGenerator
                          ref={fbxGenRef}
                          fbxFile={formData.fbxFile as File}
                          onThumbnailGenerated={(dataUrl: string) => {
                            setAutoGeneratedThumbnail(dataUrl);
                            
                            // base64를 File 객체로 변환하여 formData에 설정
                            const arr = dataUrl.split(',');
                            const mime = arr[0].match(/:(.*?);/)?.[1];
                            const bstr = atob(arr[1]);
                            let n = bstr.length;
                            const u8arr = new Uint8Array(n);
                            while (n--) {
                              u8arr[n] = bstr.charCodeAt(n);
                            }
                            const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                            
                            setFormData(prev => ({
                              ...prev,
                              thumbnail: file
                            }));
                          }}
                        />
                        {autoGeneratedThumbnail && (
                          <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center z-10 p-2">
                             <img 
                               src={autoGeneratedThumbnail} 
                               className="w-full h-full object-cover border-2 border-cyan-500 rounded-lg" 
                               alt="생성된 썸네일"
                             />
                             <button
                               type="button"
                               onClick={() => setAutoGeneratedThumbnail(null)}
                               className="absolute bottom-2 left-1/2 -translate-x-1/2 bg-red-500/90 text-white rounded-full px-3 py-1 text-xs hover:bg-red-500 transition-colors shadow-lg whitespace-nowrap"
                             >
                               ✕ 다시 촬영
                             </button>
                          </div>
                        )}
                        {!autoGeneratedThumbnail && (
                          <div className="absolute bottom-2 right-2 z-20">
                            <button
                              type="button"
                              onClick={() => fbxGenRef.current?.generateThumbnail()}
                              className="bg-cyan-600 hover:bg-cyan-500 text-white text-[10px] px-2 py-1 rounded shadow-lg border border-cyan-400/50 flex items-center gap-1 transition-all active:scale-95"
                            >
                              📸 캡처
                            </button>
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="flex flex-col items-center justify-center opacity-70">
                        <img
                          src={
                            formData.type === "vc_plugin" ||
                            formData.type === "vc_model"
                              ? "/images/ic-vc.png"
                              : formData.type === "ns_plugin" ||
                                formData.type === "ns_model"
                              ? "/images/ic-ns.png"
                              : "/images/ic-etc.png"
                          }
                          alt="기본 썸네일"
                          className="w-20 h-20 mb-4 object-contain opacity-90"
                        />
                        <span className="text-sm text-gray-400 font-medium tracking-wide">
                          시스템 썸네일 자동 적용
                        </span>
                      </div>
                    )}
                  </div>
                </div>

                {/* 오른쪽: 직접 썸네일 업로드 섹션 */}
                <div className="flex flex-col justify-center">
                  <h4 className="text-white font-medium mb-2 text-base">
                    직접 썸네일 설정 <span className="text-gray-400 text-xs font-normal ml-1">(선택항목)</span>
                  </h4>
                  <p className="text-gray-400 text-xs mb-4 leading-relaxed">
                    직접 이미지를 업로드하지 않으면 상단의 {formData.fbxFile ? '캡처본' : '기본 아이콘'}이 썸네일로 사용됩니다.
                  </p>
                  
                  <div className="relative">
                    <input
                      type="file"
                      id="thumbnail-upload"
                      name="thumbnail"
                      accept="image/*"
                      onChange={handleFileChange}
                      className="hidden"
                    />
                    <label 
                      htmlFor="thumbnail-upload"
                      className="w-full cursor-pointer bg-gray-900 hover:bg-gray-750 text-gray-300 p-3 rounded-lg border border-gray-700/50 transition-all text-xs flex items-center justify-between group"
                    >
                      <span className="truncate">{formData.thumbnail ? formData.thumbnail.name : '파일을 선택하세요'}</span>
                      <span className="bg-gray-700 group-hover:bg-gray-600 px-2 py-1 rounded text-[10px] text-white shrink-0 ml-2">파일 찾기</span>
                    </label>
                  </div>
                  <p className="text-gray-500 text-[10px] mt-2">
                    💡 1:1 비율의 JPG, PNG 권장
                  </p>
                </div>
              </div>
            </div>
          )}

          <div className="flex justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2.5 rounded-lg border border-gray-600/50 bg-gray-800/50 text-gray-300 hover:bg-gray-700 hover:text-white transition-all font-medium backdrop-blur-sm"
            >
              취소
            </button>
            <button
              type="submit"
              className="px-6 py-2.5 rounded-lg bg-cyan-600/90 hover:bg-cyan-500 border border-cyan-400/50 text-white font-medium shadow-[0_0_15px_rgba(8,145,178,0.3)] transition-all"
            >
              등록
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ComponentModal;
