"use client";

import Image from "next/image";
import { TComponentFormData } from "@/app/_types/manage/manage.types";
import React, { useState, useEffect, useRef } from "react";
import FbxThumbnailGenerator, { FbxThumbnailGeneratorRef } from "../../_components/common/FbxThumbnailGenerator";
import VideoThumbnail, { isVideoThumbnail } from "../../_components/common/VideoThumbnail";

// 카테고리 타입 정의
interface Category {
  id: number;
  name: string;
}

interface ComponentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (formData: TComponentFormData) => void;
  categories: Category[];
  type: "vc_plugin" | "ns_plugin" | "vc_model" | "ns_model" | "etc";
}

const ComponentModal = ({
  isOpen,
  onClose,
  onSubmit,
  type,
}: ComponentModalProps) => {
  const [formData, setFormData] = useState<TComponentFormData>({
    thumbnail: null,
    componentName: "",
    version: "0.0.1",
    description: "",
    features: "",
    environment: "",
    sourceFile: null,
    fbxFile: null,
    categoryId: "",
    subCategoryId: "",
    type: type,
    modelType: "component",
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [iconPreview, setIconPreview] = useState<string | null>(null);
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const fbxGenRef = useRef<FbxThumbnailGeneratorRef>(null);

  // 모달이 열릴 때마다 폼 초기화
  useEffect(() => {
    if (isOpen) {
      setFormData({
        thumbnail: null,
        componentName: "",
        version: "0.0.1",
        description: "",
        features: "",
        environment: "",
        sourceFile: null,
        fbxFile: null,
        categoryId: "",
        subCategoryId: "",
        type: type,
      });
      setThumbnailPreview(null);
      setIconPreview(null);
      setAutoGeneratedThumbnail(null);
      setIsSubmitting(false);
      setErrors({});
    }
  }, [isOpen, type]);

  const handleInputChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    const { name, value } = e.target;

    // 타입이 변경되는 경우 모든 필드와 파일 초기화
    if (name === "type") {
      setFormData({
        thumbnail: null,
        componentName: "",
        version: "0.0.1",
        description: "",
        features: "",
        environment: "",
        sourceFile: null,
        fbxFile: null,
        categoryId: "",
        subCategoryId: "",
        type: value as TComponentFormData["type"],
        modelType: "component",
      });
      setThumbnailPreview(null);
      setIconPreview(null);
      setAutoGeneratedThumbnail(null);
      setErrors({});
      return;
    }

    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, files } = e.target;
    if (files && files.length > 0) {
      const file = files[0];
      const ext = file.name.split('.').pop()?.toLowerCase();
      
      if (name === "iconFile") {
        if (!['svg', 'png', 'jpeg', 'jpg'].includes(ext || '')) {
          alert('Icon 파일은 svg, png, jpeg, jpg 확장자만 업로드 가능합니다.');
          e.target.value = '';
          return;
        }
      }

      // VC Model 확장자 체크
      if (formData.type === "vc_model") {
        if (name === "sourceFile" && ext !== "vcmx") {
          alert("VC Model의 소스 파일은 .vcmx 확장자만 가능합니다.");
          e.target.value = "";
          return;
        }
        if (name === "fbxFile" && ext !== "fbx") {
          alert("FBX 파일은 .fbx 확장자만 가능합니다.");
          e.target.value = "";
          return;
        }
      }

      setFormData({
        ...formData,
        [name]: file,
      });

      // 썸네일 이미지인 경우 미리보기 생성
      if (name === "thumbnail") {
        const reader = new FileReader();
        reader.onload = () => {
          setThumbnailPreview(reader.result as string);
          setAutoGeneratedThumbnail(null); // 수동 썸네일 선택 시 자동 생성 썸네일 제거
        };
        reader.readAsDataURL(files[0]);
      }

      // 아이콘 이미지인 경우 미리보기 생성
      if (name === "iconFile") {
        const reader = new FileReader();
        reader.onload = () => {
          setIconPreview(reader.result as string);
        };
        reader.readAsDataURL(files[0]);
      }

      // FBX 파일인 경우 (Model 타입)
      if (name === "fbxFile") {
        setAutoGeneratedThumbnail(null);
        setThumbnailPreview(null);
      }
    
      // 소스 파일이 fbx인 경우 기존 썸네일 제거
      if (name === "sourceFile") {
        setAutoGeneratedThumbnail(null); // 새 파일 선택 시 기존 썸네일 제거
        setThumbnailPreview(null); // 수동 썸네일도 제거
      }
    }
  };

  const handleFeatureChange = (value: string) => {
    setFormData({
      ...formData,
      features: value,
    });
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    // if (!formData.componentName)
    //   newErrors.componentName = "파일명은 필수입니다.";
    // if (!formData.version) newErrors.version = "버전은 필수입니다.";
    // if (!formData.categoryId) newErrors.categoryId = "카테고리는 필수입니다.";
    // if (!formData.subCategoryId)
    //   newErrors.subCategoryId = "서브 카테고리는 필수입니다.";

    if (!formData.sourceFile) {
      newErrors.sourceFile = "소스/실행 파일은 필수입니다.";
    }

    if (formData.type === "vc_plugin" && !formData.thumbnail) {
      alert("VC PlugIn 등록 시에는 MP4 또는 WebM 동영상 썸네일 첨부가 필수입니다.");
      return false;
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    if (validateForm()) {
      setIsSubmitting(true);
      try {
        const finalFormData = { ...formData };
          
        if (!finalFormData.thumbnail && !thumbnailPreview && !autoGeneratedThumbnail && finalFormData.fbxFile && fbxGenRef.current) {
            try {
                const dataUrl = await fbxGenRef.current.generateThumbnail();
                if (dataUrl && typeof dataUrl === 'string') {
                    const arr = dataUrl.split(',');
                    const mimeMatch = arr[0].match(/:(.*?);/);
                    if (mimeMatch) {
                        const mime = mimeMatch[1];
                        const bstr = atob(arr[1]);
                        let n = bstr.length;
                        const u8arr = new Uint8Array(n);
                        while (n--) {
                            u8arr[n] = bstr.charCodeAt(n);
                        }
                        const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                        finalFormData.thumbnail = file;
                    }
                }
            } catch (error) {
                console.error("자동 캡처 실패:", error);
            }
        }

        await onSubmit(finalFormData);
        // 폼 초기화 및 미리보기 초기화
        setThumbnailPreview(null);
        setIconPreview(null);
      } catch (err) {
        console.error("제출 에러:", err);
      } finally {
        setIsSubmitting(false);
      }
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center z-50">
      <div className="bg-card rounded-lg p-8 w-[800px] max-h-[90vh] overflow-y-auto relative border border-border shadow-2xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-white text-2xl"
          aria-label="닫기"
        >
          ✕
        </button>

        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label className="block text-white mb-2">타입 선택</label>
            <select
              name="type"
              value={formData.type}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            >
              <option className="bg-gray-800 text-white" value="vc_plugin">VC PlugIn</option>
              <option className="bg-gray-800 text-white" value="ns_plugin">NS PlugIn</option>
              <option className="bg-gray-800 text-white" value="vc_model">VC Model</option>
              <option className="bg-gray-800 text-white" value="ns_model">NS Model</option>
              <option className="bg-gray-800 text-white" value="etc">etc</option>
            </select>
          </div>

          {formData.type === "vc_model" && (
            <div className="mb-4">
              <label className="block text-white mb-2">모델 타입</label>
              <select
                name="modelType"
                value={formData.modelType || "component"}
                onChange={handleInputChange}
                className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
              >
                <option className="bg-gray-800 text-white" value="component">컴포넌트</option>
                <option className="bg-gray-800 text-white" value="layout">레이아웃</option>
              </select>
            </div>
          )}

          <div className="mb-4">
            <label className="block text-white mb-2">파일명</label>
            <input
              type="text"
              name="componentName"
              value={formData.componentName}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            />
            {errors.componentName && (
              <p className="text-red-500 mt-1">{errors.componentName}</p>
            )}
          </div>

          <div className="mb-4">
            <label className="block text-white mb-2">버전</label>
            <input
              type="text"
              name="version"
              value={formData.version}
              onChange={handleInputChange}
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
            />
            {errors.version && (
              <p className="text-red-500 mt-1">{errors.version}</p>
            )}
          </div>


          <div className="mb-4">
            <label className="block text-white mb-2">주요 기능</label>
            <textarea
              value={formData.features}
              onChange={(e) => handleFeatureChange(e.target.value)}
              placeholder="주요 기능을 입력하세요. (줄바꿈 가능)"
              className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all min-h-[120px] resize-y"
            />
          </div>


          {/* 파일 업로드 섹션 - 타입을 바꿀 때마다 리셋하기 위해 key={formData.type} 추가 */}
          <div key={formData.type} className="mb-6 bg-card rounded-xl border border-border p-6 shadow-sm">
            <h3 className="text-white font-semibold mb-4 flex items-center">
              파일 업로드
            </h3>

            {/* 소스/실행 파일 (설치파일) */}
            <div className="mb-4">
              <label className="block text-white mb-2">
                {formData.type === "vc_model" 
                  ? "VCMX 파일 (필수)" 
                  : formData.type === "vc_plugin"
                    ? "설치파일 (필수)"
                    : "파일 (필수)"}
              </label>
              <input
                type="file"
                name="sourceFile"
                onChange={handleFileChange}
                className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
              />
              {formData.sourceFile && (
                <p className="text-green-500 mt-1">
                  {(formData.sourceFile as File).name} 파일이 선택되었습니다.
                </p>
              )}
              {errors.sourceFile && (
                <p className="text-red-500 mt-1">{errors.sourceFile}</p>
              )}
              <p className="text-gray-400 text-sm mt-2">
                {formData.type === "vc_model" 
                  ? ".vcmx 파일을 업로드해 주세요." 
                  : formData.type === "ns_model" || formData.type === "etc"
                    ? "모든 확장자의 파일을 업로드할 수 있습니다."
                    : "모든 확장자의 파일을 원활하게 업로드할 수 있습니다. (썸네일 미등록 시 기본 썸네일이 제공됩니다)"}
              </p>
            </div>

            {/* FBX 파일 (VC Model 전용) */}
            {formData.type === "vc_model" && (
              <div className="mb-4">
                <label className="block text-white mb-2">
                  FBX 파일 (선택)
                </label>
                <input
                  type="file"
                  name="fbxFile"
                  accept=".fbx"
                  onChange={handleFileChange}
                  className="w-full bg-input text-foreground p-2 rounded border border-input-border focus:ring-1 focus:ring-primary focus:border-primary outline-none transition-all"
                />
                {formData.fbxFile && (
                  <p className="text-green-500 mt-1">
                    {(formData.fbxFile as File).name} 파일이 선택되었습니다.
                  </p>
                )}
                <p className="text-gray-400 text-sm mt-2">
                  FBX 파일을 업로드하면 3D 뷰어 및 자동 썸네일 생성이 지원됩니다.
                </p>
              </div>
            )}
          </div>

          {/* 썸네일 설정 섹션 (NS/etc Model은 자동 생성되므로 제외) */}
          {formData.sourceFile && formData.type !== "ns_model" && formData.type !== "etc" && (
            <div className="mb-6 bg-card rounded-xl border border-border mt-4 p-6 shadow-sm">
              <h3 className="text-white font-semibold mb-4 flex items-center justify-between">
                <span>썸네일 설정</span>
                {formData.type === "vc_plugin" && (
                  <span className="bg-red-500/20 border border-red-500/60 text-red-400 text-xs px-3 py-1 rounded-full font-bold animate-pulse">
                    동영상 썸네일 필수 (MP4 / WebM)
                  </span>
                )}
              </h3>

              {formData.type === "vc_plugin" && (
                <div className="mb-5 p-4 bg-cyan-950/90 border-2 border-cyan-400 rounded-xl flex items-start gap-3 shadow-[0_0_20px_rgba(6,182,212,0.25)]">
                  <div className="text-xs leading-relaxed">
                    <div className="font-bold text-cyan-300 text-sm flex items-center gap-2 mb-1">
                      <span>[필수] VC PlugIn 동영상 썸네일 안내</span>
                      <span className="bg-cyan-400 text-black px-1.5 py-0.5 rounded text-[10px] font-extrabold uppercase">Required</span>
                    </div>
                    <p className="text-cyan-100/90">
                      VC PlugIn 등록 시에는 <strong className="text-white underline underline-offset-2 decoration-cyan-400 font-bold">MP4 또는 WebM 동영상 썸네일</strong>을 반드시 업로드하셔야 정상 등록됩니다.
                    </p>
                  </div>
                </div>
              )}

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* 썸네일 결과 (또는 기본 아이콘 / 3D 뷰어) */}
                <div className="flex flex-col items-center justify-center bg-gray-800/50 rounded-xl border border-gray-700 p-2">
                  <div className="relative w-full aspect-square max-w-[300px] bg-gray-900 rounded-2xl flex flex-col items-center justify-center border border-gray-600 overflow-hidden shadow-inner">
                    {thumbnailPreview ? (
                      <>
                        {formData.thumbnail && (isVideoThumbnail(formData.thumbnail.name) || formData.thumbnail.type?.startsWith("video/")) ? (
                          <VideoThumbnail
                            src={thumbnailPreview}
                            alt="동영상 썸네일 미리보기"
                            controls={true}
                            previewOnHover={false}
                          />
                        ) : (
                          <Image
                            src={thumbnailPreview}
                            alt="썸네일"
                            fill
                            className="object-cover"
                          />
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            setThumbnailPreview(null);
                            setFormData((prev) => ({
                              ...prev,
                              thumbnail: null,
                            }));
                          }}
                          className="absolute top-2 right-2 bg-red-500/80 text-white rounded-full w-7 h-7 flex items-center justify-center hover:bg-red-500 transition-colors shadow-lg backdrop-blur-sm z-30"
                        >
                          ✕
                        </button>
                      </>
                    ) : formData.fbxFile ? (
                      <div className="w-full h-full relative">
                        <FbxThumbnailGenerator
                          ref={fbxGenRef}
                          fbxFile={formData.fbxFile as File}
                          onThumbnailGenerated={(dataUrl: string) => {
                            setAutoGeneratedThumbnail(dataUrl);
                            
                            // base64를 File 객체로 변환하여 formData에 설정
                            const arr = dataUrl.split(',');
                            const mime = arr[0].match(/:(.*?);/)?.[1];
                            const bstr = atob(arr[1]);
                            let n = bstr.length;
                            const u8arr = new Uint8Array(n);
                            while (n--) {
                              u8arr[n] = bstr.charCodeAt(n);
                            }
                            const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                            
                            setFormData(prev => ({
                              ...prev,
                              thumbnail: file
                            }));
                          }}
                        />
                        {autoGeneratedThumbnail && (
                          <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center z-10 p-2">
                             <div className="relative w-full h-full">
                               <Image 
                                 src={autoGeneratedThumbnail} 
                                 fill
                                 className="object-cover border-2 border-cyan-500 rounded-lg" 
                                 alt="생성된 썸네일"
                               />
                             </div>
                             <button
                               type="button"
                               onClick={() => setAutoGeneratedThumbnail(null)}
                               className="absolute bottom-2 left-1/2 -translate-x-1/2 bg-red-500/90 text-white rounded-full px-3 py-1 text-xs hover:bg-red-500 transition-colors shadow-lg whitespace-nowrap"
                             >
                               ✕ 다시 촬영
                             </button>
                          </div>
                        )}
                        {!autoGeneratedThumbnail && (
                          <div className="absolute bottom-2 right-2 z-20">
                            <button
                              type="button"
                              onClick={() => fbxGenRef.current?.generateThumbnail()}
                              className="bg-cyan-600 hover:bg-cyan-500 text-white text-[10px] px-2 py-1 rounded shadow-lg border border-cyan-400/50 flex items-center gap-1 transition-all active:scale-95"
                            >
                              📸 캡처
                            </button>
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="flex flex-col items-center justify-center opacity-70">
                        <Image
                          src={
                            formData.type === "vc_plugin" ||
                            formData.type === "vc_model"
                              ? "/images/ic-vc.png"
                              : formData.type === "ns_plugin" ||
                                formData.type === "ns_model"
                              ? "/images/ic-ns.png"
                              : "/images/ic-etc.png"
                          }
                          alt="기본 썸네일"
                          width={80}
                          height={80}
                          className="mb-4 object-contain opacity-90"
                        />
                        <span className="text-sm text-gray-400 font-medium tracking-wide">
                          시스템 썸네일 자동 적용
                        </span>
                      </div>
                    )}
                  </div>
                </div>

                {/* 오른쪽: 직접 썸네일 업로드 섹션 */}
                <div className="flex flex-col justify-center">
                  <h4 className="text-white font-medium mb-2 text-base flex items-center gap-2">
                    <span>직접 썸네일 설정</span>
                    {formData.type === "vc_plugin" ? (
                      <span className="text-red-400 text-xs font-bold bg-red-950/80 border border-red-500/50 px-2 py-0.5 rounded">
                        동영상 필수 (MP4 / WebM)
                      </span>
                    ) : (
                      <span className="text-gray-400 text-xs font-normal ml-1">(선택항목)</span>
                    )}
                  </h4>
                  <p className="text-gray-400 text-xs mb-4 leading-relaxed">
                    {formData.type === "vc_plugin" 
                      ? "VC PlugIn 타입은 MP4 또는 WebM 동영상 파일 업로드가 필수입니다."
                      : `직접 이미지를 업로드하지 않으면 상단의 ${formData.fbxFile ? '캡처본' : '기본 아이콘'}이 썸네일로 사용됩니다.`}
                  </p>
                  
                  <div className="relative">
                    <input
                      type="file"
                      id="thumbnail-upload"
                      name="thumbnail"
                      accept={formData.type === "vc_plugin" ? "video/mp4,video/webm" : "image/*"}
                      onChange={handleFileChange}
                      className="hidden"
                    />
                    <label 
                      htmlFor="thumbnail-upload"
                      className={`w-full cursor-pointer p-3 rounded-lg border transition-all text-xs flex items-center justify-between group ${
                        formData.type === "vc_plugin" && !formData.thumbnail
                          ? "bg-cyan-950/40 border-cyan-500/80 hover:bg-cyan-900/50 text-cyan-200"
                          : "bg-gray-900 hover:bg-gray-750 text-gray-300 border-gray-700/50"
                      }`}
                    >
                      <span className="truncate">{formData.thumbnail ? formData.thumbnail.name : (formData.type === "vc_plugin" ? '동영상 파일 선택 (MP4, WebM)' : '파일을 선택하세요')}</span>
                      <span className="bg-cyan-600 group-hover:bg-cyan-500 px-2 py-1 rounded text-[10px] text-white shrink-0 ml-2 font-medium">파일 찾기</span>
                    </label>
                  </div>
                  <p className="text-gray-500 text-[10px] mt-2">
                    {formData.type === "vc_plugin" ? "💡 MP4, WebM 동영상 권장" : "💡 1:1 비율 권장"}
                  </p>
                </div>
              </div>
            </div>
          )}

          <div className="flex justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-6 py-2.5 rounded-lg border border-gray-600/50 bg-gray-800/50 text-gray-300 hover:bg-gray-700 hover:text-white transition-all font-medium backdrop-blur-sm disabled:opacity-50"
            >
              취소
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="px-6 py-2.5 rounded-lg bg-cyan-600/90 hover:bg-cyan-500 border border-cyan-400/50 text-white font-medium shadow-[0_0_15px_rgba(8,145,178,0.3)] transition-all disabled:opacity-50 flex items-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>업로드 중...</span>
                </>
              ) : (
                "등록"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ComponentModal;
