"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import useUserStore from "@/app/stores/UserStore";
import Image from "next/image";
import VideoThumbnail, { isVideoThumbnail } from "../../../_components/common/VideoThumbnail";
import FbxThumbnailGenerator, { FbxThumbnailGeneratorRef } from "../../../_components/common/FbxThumbnailGenerator";
import { useAlertStore } from "@/app/stores/alertStore";
import { authenticatedFetch } from "@/app/utils/api";

const isSupportedVideoFile = (file: File) =>
  Boolean(
    file &&
      (file.type?.startsWith("video/") ||
        /\.(mp4|webm|mov|mkv|avi)$/i.test(file.name))
  );

const isPlaceholderThumbnail = (url?: string) => {
  if (!url) return true;
  const placeholders = [
    "/images/ic-vc.png",
    "/images/ic-ns.png",
    "/images/ic-etc.png",
    "/uploads/thumbnails/ic-vc.png",
    "/uploads/thumbnails/ic-ns.png",
    "/uploads/thumbnails/ic-etc.png",
  ];
  return placeholders.some((placeholder) => url.includes(placeholder));
};

interface VersionUpdateModalProps {
  isOpen: boolean;
  onClose: () => void;
  componentId: number;
  onSuccess?: () => void;
  initialData?: {
    version: string;
    description: string;
    mainFeatures: string[];
    recommendedEnvironment: string;
    thumbnailImage?: string;
    fileLinks?: {
      source?: string;
      icon?: string;
      fbx?: string;
      vcmx?: string;
    };
    fileName?: string;
    modelType?: string;
  };
  componentType: string;
}
const VersionUpdateModal = ({
  isOpen,
  onClose,
  componentId,
  onSuccess,
  initialData,
  componentType,
}: VersionUpdateModalProps) => {
  const router = useRouter();
  const getAccessToken = useUserStore((state) => state.getAccessToken);

  // 버전 증가 함수
  const incrementVersion = useCallback((currentVersion: string): string => {
    const parts = currentVersion.split(".").map(Number);

    // 패치 버전 증가 (0.0.1 -> 0.0.2)
    parts[2] = (parts[2] || 0) + 1;

    // 마이너 버전 증가 (0.0.9 -> 0.1.0)
    if (parts[2] > 9) {
      parts[2] = 0;
      parts[1] = (parts[1] || 0) + 1;
    }

    // 메이저 버전 증가 (0.9.9 -> 1.0.0)
    if (parts[1] > 9) {
      parts[1] = 0;
      parts[0] = (parts[0] || 0) + 1;
    }

    return parts.join(".");
  }, []);

const formatFeaturesText = (raw: any): string => {
  if (!raw) return "";
  let list: string[] = [];

  if (Array.isArray(raw)) {
    list = raw.flatMap((item) => (typeof item === "string" ? item.split("\n") : [String(item)]));
  } else if (typeof raw === "string") {
    const trimmed = raw.trim();
    if (!trimmed) return "";
    if (trimmed.startsWith("[") || trimmed.startsWith("{")) {
      try {
        const parsed = JSON.parse(trimmed);
        if (Array.isArray(parsed)) {
          list = parsed.flatMap((item) => (typeof item === "string" ? item.split("\n") : [String(item)]));
        } else {
          list = [String(parsed)];
        }
      } catch (e) {
        list = trimmed.split("\n");
      }
    } else {
      list = trimmed.split("\n");
    }
  } else {
    list = [String(raw)];
  }

  return list
    .map((s) => s.replace(/\r/g, "").replace(/^["']|["']$/g, "").trim())
    .filter(Boolean)
    .join("\n");
};

  const [formData, setFormData] = useState({
    componentName: initialData?.fileName || "",
    version: initialData?.version || "",
    description: initialData?.description || "",
    mainFeatures: formatFeaturesText(initialData?.mainFeatures),
    recommendedEnvironment: initialData?.recommendedEnvironment || "",
    modelType: initialData?.modelType || "component",
  });

  const [files, setFiles] = useState<{
    thumbnail?: File;
    source?: File;
    icon?: File;
    fbx?: File;
  }>({});

  const [useExistingSource, setUseExistingSource] = useState(true);
  const [useExistingIcon, setUseExistingIcon] = useState(true);
  const [useExistingFbx, setUseExistingFbx] = useState(true);
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [iconPreview, setIconPreview] = useState<string | null>(null);
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<
    string | null
  >(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [existingFiles] = useState({
    source: initialData?.fileLinks?.source || "",
    icon: initialData?.fileLinks?.icon || "",
    fbx: initialData?.fileLinks?.fbx || "",
  });

  const sourceFileInputRef = useRef<HTMLInputElement>(null);
  const fbxGenRef = useRef<FbxThumbnailGeneratorRef>(null);

  // 모달이 열릴 때 자동으로 다음 버전 계산 및 상태 초기화
  useEffect(() => {
    if (isOpen) {
      const nextVersion = initialData?.version ? incrementVersion(initialData.version) : "1.0.0";
      setFormData({
        componentName: initialData?.fileName || "",
        version: nextVersion,
        description: initialData?.description || "",
        mainFeatures: formatFeaturesText(initialData?.mainFeatures),
        recommendedEnvironment: initialData?.recommendedEnvironment || "",
        modelType: initialData?.modelType || "component",
      });

      // 파일 상태 초기화
      setFiles({});
      setUseExistingSource(true);
      setUseExistingIcon(true);
      setUseExistingFbx(true);

      // 기존 썸네일 미리보기 설정
      if (initialData?.thumbnailImage && !isPlaceholderThumbnail(initialData.thumbnailImage)) {
        const thumbnailUrl = initialData.thumbnailImage.startsWith("http")
          ? initialData.thumbnailImage
          : `${process.env.NEXT_PUBLIC_API_URL}${initialData.thumbnailImage}`;
        setThumbnailPreview(thumbnailUrl);
      } else {
        setThumbnailPreview(null);
      }

      setAutoGeneratedThumbnail(null);

      // 기존 아이콘 미리보기 설정
      if (initialData?.fileLinks?.icon) {
        const iconUrl = initialData.fileLinks.icon.startsWith("http")
          ? initialData.fileLinks.icon
          : `${process.env.NEXT_PUBLIC_API_URL}${initialData.fileLinks.icon}`;
        setIconPreview(iconUrl);
      } else {
        setIconPreview(null);
      }
    }
  }, [isOpen]);

  const handleThumbnailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    const { showAlert } = useAlertStore.getState();
    if (file) {
      if (componentType === "vc_plugin" && !isSupportedVideoFile(file)) {
        showAlert("VC PlugIn 썸네일은 MP4 또는 WebM 동영상만 등록할 수 있습니다.", { title: "형식 오류", type: "warning" });
        e.target.value = "";
        return;
      }

      if (componentType !== "vc_plugin" && !file.type.startsWith("image/")) {
        showAlert("썸네일은 이미지 파일만 등록할 수 있습니다.", { title: "형식 오류", type: "warning" });
        e.target.value = "";
        return;
      }

      setFiles((prev) => ({ ...prev, thumbnail: file }));
      const previewUrl = URL.createObjectURL(file);
      setThumbnailPreview(previewUrl);
      setAutoGeneratedThumbnail(null); // 수동 썸네일 선택 시 자동 생성 썸네일 제거
    }
  };

  const handleClose = () => {
    if (thumbnailPreview && thumbnailPreview.startsWith("blob:")) {
      URL.revokeObjectURL(thumbnailPreview);
    }
    setThumbnailPreview(null);
    setIconPreview(null);
    setAutoGeneratedThumbnail(null);
    onClose();
  };

  // 제출 함수 (신규 등록과 동일한 방식)
  const onSubmit = async (submittedFiles: typeof files) => {
    const accessToken = getAccessToken();
    const { showAlert, showToast } = useAlertStore.getState();

    if (!accessToken) {
      showAlert("로그인이 필요한 서비스입니다.", { title: "접근 제한", type: "warning" });
      return;
    }

    try {
      const formDataToSend = new FormData();

      // 기본 데이터 추가
      formDataToSend.append("type", componentType);
      formDataToSend.append("componentName", formData.componentName);
      formDataToSend.append("version", formData.version);
      formDataToSend.append("description", formData.description);
      formDataToSend.append("environment", formData.recommendedEnvironment);

      if (componentType === "vc_model") {
        formDataToSend.append("modelType", formData.modelType);
      }

      // features 추가 (한 블록으로 전송)
      formDataToSend.append("features", formData.mainFeatures);

      if (submittedFiles.thumbnail) {
        formDataToSend.append("thumbnail", submittedFiles.thumbnail);
        console.log("썸네일 FormData에 추가됨");
      }

      // 소스 파일 처리
      if (useExistingSource && existingFiles.source) {
        // 기존 소스 파일 사용 시 경로 전송
        formDataToSend.append("useExistingSource", "true");
        formDataToSend.append("existingSourcePath", existingFiles.source);
      } else if (submittedFiles.source) {
        // 새 소스 파일 선택 시
        formDataToSend.append("sourceFile", submittedFiles.source);
      }



      // FBX 파일 처리 (VC Model)
      if (useExistingFbx && existingFiles.fbx) {
        formDataToSend.append("useExistingFbx", "true");
        formDataToSend.append("existingFbxPath", existingFiles.fbx);
      } else if (submittedFiles.fbx) {
        formDataToSend.append("fbxFile", submittedFiles.fbx);
      }

      const response = await authenticatedFetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/components/${componentId}`,
        {
          method: "PATCH",
          body: formDataToSend,
        }
      );

      const data = await response.json();

      if (data.success) {
        showToast("버전이 업데이트되었습니다.", "success");
        handleClose();

        // 최신 버전 페이지로 리다이렉션
        if (data.data?.latestVersion?.id) {
          router.push(`/manage/${data.data.latestVersion.id}`);
        } else if (onSuccess) {
          onSuccess();
        }
      } else {
        showAlert(data.message || "버전 업데이트에 실패했습니다.", { title: "업데이트 실패", type: "error" });
      }
    } catch (error) {
      console.error("버전 업데이트 중 오류 발생:", error);
      showAlert("버전 업데이트 중 오류가 발생했습니다.", { title: "오류 발생", type: "error" });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const accessToken = getAccessToken();
    const { showAlert } = useAlertStore.getState();

    if (!accessToken) {
      showAlert("로그인이 필요한 서비스입니다.", { title: "접근 제한", type: "warning" });
      return;
    }

    if (!files.source && !useExistingSource) {
      showAlert("소스/실행 파일은 필수입니다.", { title: "필수 입력 누락", type: "warning" });
      return;
    }

    const finalFiles = { ...files };

    const isFbxActive = files.fbx || (useExistingFbx && existingFiles.fbx);
    if (!finalFiles.thumbnail && !thumbnailPreview && !autoGeneratedThumbnail && isFbxActive && fbxGenRef.current) {
        try {
            const dataUrl = await fbxGenRef.current.generateThumbnail();
            if (dataUrl && typeof dataUrl === 'string') {
                const arr = dataUrl.split(',');
                const mimeMatch = arr[0].match(/:(.*?);/);
                if (mimeMatch) {
                    const mime = mimeMatch[1];
                    const bstr = atob(arr[1]);
                    let n = bstr.length;
                    const u8arr = new Uint8Array(n);
                    while (n--) {
                        u8arr[n] = bstr.charCodeAt(n);
                    }
                    const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                    finalFiles.thumbnail = file;
                }
            }
        } catch (error) {
            console.error("자동 캡처 실패:", error);
        }
    }

    try {
      setIsSubmitting(true);
      await onSubmit(finalFiles);
    } catch (err) {
      console.error("업데이트 제출 에러:", err);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      {/* 업로드 중 로딩 오버레이 (화면 중앙 fixed 배치) */}
      {isSubmitting && (
        <div className="fixed inset-0 bg-black/85 backdrop-blur-md flex flex-col items-center justify-center z-[100] p-6 text-center">
          <div className="w-14 h-14 border-4 border-cyan-500 border-t-transparent rounded-full animate-spin mb-4 shadow-[0_0_20px_rgba(6,182,212,0.6)]" />
          <h4 className="text-white font-bold text-lg mb-2">버전 정보를 서버로 업로드하는 중입니다...</h4>
          <p className="text-cyan-200 text-xs leading-relaxed max-w-sm">
            파일 크기에 따라 소요 시간이 길어질 수 있습니다.<br />
            업로드가 완료될 때까지 창을 닫거나 새로고침하지 마세요.
          </p>
        </div>
      )}

      <div className="bg-gray-800 rounded-2xl p-6 w-[600px] max-h-[85vh] overflow-y-auto relative shadow-2xl">

        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-bold text-white">새 버전 등록</h2>
          <button
            onClick={handleClose}
            disabled={isSubmitting}
            className="text-gray-400 hover:text-white transition-colors disabled:opacity-50"
          >
            ✕
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* 1. 기본 정보 그룹 */}
          <div className="bg-gray-800/60 p-4 rounded-xl border border-gray-700/60 space-y-4">
            <h3 className="text-blue-400 font-semibold text-sm flex items-center gap-2 border-b border-gray-700/60 pb-2">
              <span>기본 정보</span>
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1.5">
                  컴포넌트 이름 <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={formData.componentName}
                  onChange={(e) =>
                    setFormData({ ...formData, componentName: e.target.value })
                  }
                  className="w-full px-3 py-2 bg-gray-900/90 border border-gray-700 rounded-lg text-white focus:outline-none focus:border-blue-500 transition-colors"
                  placeholder="컴포넌트 이름을 입력하세요"
                />
                <p className="text-gray-400 text-[11px] mt-1">
                  이름을 변경하시면 해당 컴포넌트의 모든 버전 이름이 함께 변경됩니다.
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1.5">
                  업데이트 버전 <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={formData.version}
                  onChange={(e) =>
                    setFormData({ ...formData, version: e.target.value })
                  }
                  className="w-full px-3 py-2 bg-gray-900/90 border border-gray-700 rounded-lg text-white focus:outline-none focus:border-blue-500 font-mono transition-colors"
                  placeholder="예: 1.0.1"
                />
              </div>
            </div>

            {/* 모델 타입 (VC Model 전용) */}
            {componentType === "vc_model" && (
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1.5">
                  모델 타입
                </label>
                <select
                  value={formData.modelType}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, modelType: e.target.value }))
                  }
                  className="w-full px-3 py-2 bg-gray-900/90 border border-gray-700 rounded-lg text-white focus:border-blue-500 outline-none transition-colors"
                >
                  <option value="component">컴포넌트</option>
                  <option value="layout">레이아웃</option>
                </select>
              </div>
            )}
          </div>

          {/* 2. 파일 첨부 그룹 */}
          <div className="bg-gray-800/60 p-4 rounded-xl border border-gray-700/60 space-y-4">
            <h3 className="text-blue-400 font-semibold text-sm flex items-center gap-2 border-b border-gray-700/60 pb-2">
              <span>파일 첨부</span>
            </h3>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1.5">
                {componentType === "vc_model" ? "VCMX 파일 (필수)" : componentType === "vc_plugin" ? "설치파일 (필수)" : "파일 (필수)"}
              </label>
              {existingFiles.source && (
                <div className="mb-2.5 p-2.5 bg-gray-900/80 rounded-lg border border-gray-700/70 flex items-center justify-between">
                  <span className="text-xs text-gray-400 truncate">
                    현재 파일: <strong className="text-gray-200 font-mono">{`${initialData?.fileName || '파일'}_v${initialData?.version || '1.0.0'}.${existingFiles.source.split('.').pop() || 'exe'}`}</strong>
                  </span>
                  <label className="flex items-center space-x-2 cursor-pointer shrink-0">
                    <input
                      type="checkbox"
                      checked={useExistingSource}
                      onChange={(e) => {
                        setUseExistingSource(e.target.checked);
                        if (e.target.checked) {
                          setFiles((prev) => ({ ...prev, source: undefined }));
                          if (sourceFileInputRef.current) {
                            sourceFileInputRef.current.value = "";
                          }
                          if (initialData?.thumbnailImage && !isPlaceholderThumbnail(initialData.thumbnailImage)) {
                            const thumbnailUrl =
                              initialData.thumbnailImage.startsWith("http")
                                ? initialData.thumbnailImage
                                : `${process.env.NEXT_PUBLIC_API_URL}${initialData.thumbnailImage}`;
                            setThumbnailPreview(thumbnailUrl);
                          } else {
                            setThumbnailPreview(null);
                          }
                        }
                      }}
                      className="w-4 h-4 text-cyan-600 bg-gray-700 border-gray-600 rounded focus:ring-cyan-500"
                    />
                    <span className="text-xs text-cyan-300 font-medium">기존 파일 사용</span>
                  </label>
                </div>
              )}
              <input
                ref={sourceFileInputRef}
                type="file"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) {
                    const ext = file.name.split('.').pop()?.toLowerCase();
                    if (componentType === "vc_model" && ext !== "vcmx") {
                      useAlertStore.getState().showAlert("VC Model의 소스 파일은 .vcmx 확장자만 가능합니다.", { title: "형식 오류", type: "warning" });
                      e.target.value = "";
                      return;
                    }
                    
                    setFiles((prev) => ({ ...prev, source: file }));
                    setUseExistingSource(false);
                    setAutoGeneratedThumbnail(null);
                  }
                }}
                className="w-full px-3 py-2 bg-gray-900/90 border border-gray-700 rounded-lg text-white text-sm"
              />
            </div>

            {/* FBX 파일 (VC Model 전용) */}
            {componentType === "vc_model" && (
              <div className="pt-2">
                <label className="block text-sm font-medium text-gray-300 mb-1.5">
                  FBX 파일 (선택)
                </label>
                {existingFiles.fbx && (
                  <div className="mb-2 p-2 bg-gray-900/80 rounded-lg border border-gray-700 flex items-center justify-between">
                    <span className="text-xs text-gray-400 truncate">
                      현재 FBX: <strong className="text-gray-200 font-mono">{`${initialData?.fileName || '파일'}_v${initialData?.version || '1.0.0'}.fbx`}</strong>
                    </span>
                    <label className="flex items-center space-x-2 cursor-pointer shrink-0">
                      <input
                        type="checkbox"
                        checked={useExistingFbx}
                        onChange={(e) => {
                          setUseExistingFbx(e.target.checked);
                          if (e.target.checked) {
                            setFiles((prev) => ({ ...prev, fbx: undefined }));
                          }
                        }}
                        className="w-4 h-4 text-cyan-600 bg-gray-700 border-gray-600 rounded focus:ring-cyan-500"
                      />
                      <span className="text-xs text-cyan-300">기존 FBX 사용</span>
                    </label>
                  </div>
                )}
                <input
                  type="file"
                  accept=".fbx"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                      const ext = file.name.split('.').pop()?.toLowerCase();
                      if (ext !== "fbx") {
                        useAlertStore.getState().showAlert("FBX 파일은 .fbx 확장자만 가능합니다.", { title: "형식 오류", type: "warning" });
                        e.target.value = "";
                        return;
                      }

                      setFiles((prev) => ({ ...prev, fbx: file }));
                      setUseExistingFbx(false);
                      setThumbnailPreview("");
                      setAutoGeneratedThumbnail(null);
                    }
                  }}
                  className="w-full px-3 py-2 bg-gray-900/90 border border-gray-700 rounded-lg text-white text-sm"
                />
              </div>
            )}
          </div>

          {/* 3. 썸네일 설정 그룹 (NS/etc Model 제외) */}
          {componentType !== "ns_model" && componentType !== "etc" && (
            <div className="bg-gray-800/60 p-4 rounded-xl border border-gray-700/60 space-y-4">
              <h3 className="text-cyan-400 font-semibold text-sm flex items-center justify-between border-b border-gray-700/60 pb-2">
                <span>썸네일 설정</span>
                {componentType === "vc_plugin" && (
                  <span className="bg-cyan-500/20 border border-cyan-500/60 text-cyan-300 text-xs px-2.5 py-0.5 rounded-full font-bold">
                    동영상 썸네일 (MP4 / WebM)
                  </span>
                )}
              </h3>

              {componentType === "vc_plugin" && (
                <div className="p-3 bg-cyan-950/80 border border-cyan-500/40 rounded-lg text-xs leading-relaxed text-cyan-200">
                  VC PlugIn 업데이트 시 새로운 썸네일을 첨부하지 않으면 <strong className="text-white">직전 최신 버전의 동영상 썸네일</strong>이 그대로 유지됩니다.
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
                {/* 썸네일 미리보기 영역 */}
                <div className="flex flex-col items-center justify-center bg-gray-900/80 rounded-xl border border-gray-700 p-3">
                  <div className="relative w-full aspect-square max-w-[240px] bg-gray-950 rounded-lg flex flex-col items-center justify-center border border-gray-700 overflow-hidden">
                    {thumbnailPreview ? (
                      <>
                        {isVideoThumbnail(thumbnailPreview) || (files.thumbnail && isSupportedVideoFile(files.thumbnail)) ? (
                          <VideoThumbnail
                            src={thumbnailPreview}
                            alt="썸네일"
                          />
                        ) : (
                          <Image
                            src={thumbnailPreview}
                            alt="썸네일"
                            fill
                            className="object-cover"
                            unoptimized
                          />
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            if (thumbnailPreview?.startsWith("blob:")) {
                              URL.revokeObjectURL(thumbnailPreview);
                            }
                            setThumbnailPreview("");
                            setFiles((prev) => ({
                              ...prev,
                              thumbnail: undefined,
                            }));
                          }}
                          className="absolute top-2 right-2 bg-red-500/80 text-white rounded-full w-6 h-6 flex items-center justify-center text-xs hover:bg-red-500 transition-colors shadow-lg z-30"
                        >
                          ✕
                        </button>
                      </>
                    ) : (files.fbx || (useExistingFbx && existingFiles.fbx)) ? (
                      <div className="w-full h-full relative">
                        <FbxThumbnailGenerator
                          ref={fbxGenRef}
                          fbxFile={files.fbx}
                          fbxUrl={useExistingFbx && existingFiles.fbx ? `${process.env.NEXT_PUBLIC_API_URL}${existingFiles.fbx}` : null}
                          onThumbnailGenerated={(dataUrl: string) => {
                            setAutoGeneratedThumbnail(dataUrl);
                          }}
                        />
                        {autoGeneratedThumbnail && (
                          <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center z-10 p-2">
                            <div className="relative w-full h-full">
                             <Image 
                               src={autoGeneratedThumbnail} 
                               fill
                               className="object-cover border-2 border-cyan-500 rounded-lg" 
                               alt="생성된 썸네일"
                               unoptimized
                             />
                            </div>
                             <button
                               type="button"
                               onClick={() => {
                                 setAutoGeneratedThumbnail(null);
                                 setFiles(prev => ({ ...prev, thumbnail: undefined }));
                               }}
                               className="absolute bottom-2 left-1/2 -translate-x-1/2 bg-red-500/90 text-white rounded-full px-3 py-1 text-xs hover:bg-red-500 transition-colors shadow-lg whitespace-nowrap"
                             >
                               ✕ 다시 촬영
                             </button>
                          </div>
                        )}
                        {!autoGeneratedThumbnail && (
                          <div className="absolute bottom-2 right-2 z-20">
                            <button
                              type="button"
                              onClick={async () => {
                                if (fbxGenRef.current) {
                                  const dataUrl = await fbxGenRef.current.generateThumbnail();
                                  if (dataUrl) {
                                    setAutoGeneratedThumbnail(dataUrl);
                                    const arr = dataUrl.split(',');
                                    const mime = arr[0].match(/:(.*?);/)?.[1];
                                    const bstr = atob(arr[1]);
                                    let n = bstr.length;
                                    const u8arr = new Uint8Array(n);
                                    while (n--) {
                                      u8arr[n] = bstr.charCodeAt(n);
                                    }
                                    const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                                    setFiles(prev => ({ ...prev, thumbnail: file }));
                                  }
                                }
                              }}
                              className="bg-cyan-600 hover:bg-cyan-500 text-white text-[10px] px-2 py-1 rounded shadow-lg border border-cyan-400/50 flex items-center gap-1 transition-all"
                            >
                              화면 캡처
                            </button>
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="w-full h-full relative">
                        <ThumbnailPlaceholder type={componentType} name={initialData?.version} />
                      </div>
                    )}
                  </div>
                </div>

                {/* 썸네일 파일 업로드 */}
                <div className="flex flex-col justify-center space-y-2">
                  <label className="block text-sm font-medium text-gray-300">
                    새 썸네일 업로드
                  </label>
                  <div className="relative">
                    <input
                      type="file"
                      id="update-thumbnail-upload-new"
                      name="thumbnail"
                      accept={componentType === "vc_plugin" ? "video/mp4,video/webm" : "image/*"}
                      onChange={handleThumbnailChange}
                      className="hidden"
                    />
                    <label 
                      htmlFor="update-thumbnail-upload-new"
                      className="w-full cursor-pointer p-3 rounded-lg border border-gray-700 bg-gray-900 hover:bg-gray-800 text-gray-300 transition-colors text-xs flex items-center justify-between group"
                    >
                      <span className="truncate">
                        {files.thumbnail ? files.thumbnail.name : (componentType === "vc_plugin" ? "동영상 선택 (MP4, WebM)" : "이미지 선택")}
                      </span>
                      <span className="bg-cyan-600 group-hover:bg-cyan-500 px-2.5 py-1 rounded text-[11px] text-white shrink-0 font-medium">파일 선택</span>
                    </label>
                  </div>
                  <p className="text-gray-400 text-[11px]">
                    {componentType === "vc_plugin" ? "MP4, WebM 동영상 썸네일 지원" : "이미지 썸네일 지원"}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* 4. 상세 내용 그룹 */}
          <div className="bg-gray-800/60 p-4 rounded-xl border border-gray-700/60 space-y-4">
            <h3 className="text-cyan-400 font-semibold text-sm flex items-center gap-2 border-b border-gray-700/60 pb-2">
              <span>상세 내용</span>
            </h3>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1.5">
                주요 기능 (줄바꿈으로 구분)
              </label>
              <textarea
                value={formData.mainFeatures}
                onChange={(e) =>
                  setFormData((prev) => ({
                    ...prev,
                    mainFeatures: e.target.value,
                  }))
                }
                className="w-full px-3 py-2 bg-gray-900/90 border border-gray-700 rounded-lg text-white h-24 resize-none focus:outline-none focus:border-cyan-500 text-sm leading-relaxed"
                placeholder="주요 기능 내용을 줄바꿈으로 작성해 주세요..."
              />
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-4 border-t border-gray-700">
            <button
              type="button"
              onClick={handleClose}
              disabled={isSubmitting}
              className="px-5 py-2 rounded-lg border border-gray-600/50 bg-gray-800/50 text-gray-300 hover:bg-gray-700 hover:text-white transition-all font-medium text-sm disabled:opacity-50"
            >
              취소
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="px-6 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 border border-cyan-400/50 text-white font-medium text-sm shadow-[0_0_15px_rgba(8,145,178,0.3)] transition-all disabled:opacity-50 flex items-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>업로드 중...</span>
                </>
              ) : (
                "새 버전 업로드"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default VersionUpdateModal;
