"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import useUserStore from "@/app/stores/UserStore";
import Image from "next/image";
import VideoThumbnail, { isVideoThumbnail } from "../../../_components/common/VideoThumbnail";
import FbxThumbnailGenerator, { FbxThumbnailGeneratorRef } from "../../../_components/common/FbxThumbnailGenerator";
import ThumbnailPlaceholder from "../../../_components/common/ThumbnailPlaceholder";
import { useAlertStore } from "@/app/stores/alertStore";

const isSupportedVideoFile = (file: File) =>
  ["video/mp4", "video/webm"].includes(file.type) && /\.(mp4|webm)$/i.test(file.name);

const isPlaceholderThumbnail = (url?: string) => {
  if (!url) return true;
  const placeholders = [
    "/images/ic-vc.png",
    "/images/ic-ns.png",
    "/images/ic-etc.png",
    "/uploads/thumbnails/ic-vc.png",
    "/uploads/thumbnails/ic-ns.png",
    "/uploads/thumbnails/ic-etc.png",
  ];
  return placeholders.some((placeholder) => url.includes(placeholder));
};

interface VersionUpdateModalProps {
  isOpen: boolean;
  onClose: () => void;
  componentId: number;
  onSuccess?: () => void;
  initialData?: {
    version: string;
    description: string;
    mainFeatures: string[];
    recommendedEnvironment: string;
    thumbnailImage?: string;
    fileLinks?: {
      source?: string;
      icon?: string;
      fbx?: string;
      vcmx?: string;
    };
    fileName?: string;
    modelType?: string;
  };
  componentType: string;
}
const VersionUpdateModal = ({
  isOpen,
  onClose,
  componentId,
  onSuccess,
  initialData,
  componentType,
}: VersionUpdateModalProps) => {
  const router = useRouter();
  const getAccessToken = useUserStore((state) => state.getAccessToken);

  // 버전 증가 함수
  const incrementVersion = useCallback((currentVersion: string): string => {
    const parts = currentVersion.split(".").map(Number);

    // 패치 버전 증가 (0.0.1 -> 0.0.2)
    parts[2] = (parts[2] || 0) + 1;

    // 마이너 버전 증가 (0.0.9 -> 0.1.0)
    if (parts[2] > 9) {
      parts[2] = 0;
      parts[1] = (parts[1] || 0) + 1;
    }

    // 메이저 버전 증가 (0.9.9 -> 1.0.0)
    if (parts[1] > 9) {
      parts[1] = 0;
      parts[0] = (parts[0] || 0) + 1;
    }

    return parts.join(".");
  }, []);

  const [formData, setFormData] = useState({
    componentName: initialData?.fileName || "",
    version: initialData?.version || "",
    description: initialData?.description || "",
    mainFeatures: initialData?.mainFeatures?.join("\n") || "",
    recommendedEnvironment: initialData?.recommendedEnvironment || "",
    modelType: initialData?.modelType || "component",
  });

  const [files, setFiles] = useState<{
    thumbnail?: File;
    source?: File;
    icon?: File;
    fbx?: File;
  }>({});

  const [useExistingSource, setUseExistingSource] = useState(true);
  const [useExistingIcon, setUseExistingIcon] = useState(true);
  const [useExistingFbx, setUseExistingFbx] = useState(true);
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [iconPreview, setIconPreview] = useState<string | null>(null);
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<
    string | null
  >(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [existingFiles] = useState({
    source: initialData?.fileLinks?.source || "",
    icon: initialData?.fileLinks?.icon || "",
    fbx: initialData?.fileLinks?.fbx || "",
  });

  const sourceFileInputRef = useRef<HTMLInputElement>(null);
  const fbxGenRef = useRef<FbxThumbnailGeneratorRef>(null);

  // 모달이 열릴 때 자동으로 다음 버전 계산 및 상태 초기화
  useEffect(() => {
    if (isOpen && initialData?.version) {
      const nextVersion = incrementVersion(initialData.version);
      setFormData((prev) => ({
        ...prev,
        componentName: initialData.fileName || "",
        version: nextVersion,
        modelType: initialData.modelType || "component",
      }));

      // 파일 상태 초기화
      setFiles({});
      setUseExistingSource(true);
      setUseExistingIcon(true);
      setUseExistingFbx(true);

      // 기존 썸네일 미리보기 설정
      if (initialData?.thumbnailImage && !isPlaceholderThumbnail(initialData.thumbnailImage)) {
        const thumbnailUrl = initialData.thumbnailImage.startsWith("http")
          ? initialData.thumbnailImage
          : `${process.env.NEXT_PUBLIC_API_URL}${initialData.thumbnailImage}`;
        setThumbnailPreview(thumbnailUrl);
      } else {
        setThumbnailPreview(null);
      }

      setAutoGeneratedThumbnail(null);

      // 기존 아이콘 미리보기 설정
      if (initialData?.fileLinks?.icon) {
        const iconUrl = initialData.fileLinks.icon.startsWith("http")
          ? initialData.fileLinks.icon
          : `${process.env.NEXT_PUBLIC_API_URL}${initialData.fileLinks.icon}`;
        setIconPreview(iconUrl);
      } else {
        setIconPreview(null);
      }
    }
  }, [
    isOpen,
    initialData?.version,
    incrementVersion,
    initialData?.thumbnailImage,
    initialData?.fileLinks?.icon,
    initialData?.fileName,
    initialData?.modelType,
  ]);

  const handleThumbnailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    const { showAlert } = useAlertStore.getState();
    if (file) {
      if (componentType === "vc_plugin" && !isSupportedVideoFile(file)) {
        showAlert("VC PlugIn 썸네일은 MP4 또는 WebM 동영상만 등록할 수 있습니다.", { title: "형식 오류", type: "warning" });
        e.target.value = "";
        return;
      }

      if (componentType !== "vc_plugin" && !file.type.startsWith("image/")) {
        showAlert("썸네일은 이미지 파일만 등록할 수 있습니다.", { title: "형식 오류", type: "warning" });
        e.target.value = "";
        return;
      }

      setFiles((prev) => ({ ...prev, thumbnail: file }));
      const previewUrl = URL.createObjectURL(file);
      setThumbnailPreview(previewUrl);
      setAutoGeneratedThumbnail(null); // 수동 썸네일 선택 시 자동 생성 썸네일 제거
    }
  };

  const handleClose = () => {
    if (thumbnailPreview && thumbnailPreview.startsWith("blob:")) {
      URL.revokeObjectURL(thumbnailPreview);
    }
    setThumbnailPreview(null);
    setIconPreview(null);
    setAutoGeneratedThumbnail(null);
    onClose();
  };

  // 제출 함수 (신규 등록과 동일한 방식)
  const onSubmit = async (submittedFiles: typeof files) => {
    const accessToken = getAccessToken();
    const { showAlert, showToast } = useAlertStore.getState();

    if (!accessToken) {
      showAlert("로그인이 필요한 서비스입니다.", { title: "접근 제한", type: "warning" });
      return;
    }

    try {
      const formDataToSend = new FormData();

      // 기본 데이터 추가
      formDataToSend.append("componentName", formData.componentName);
      formDataToSend.append("version", formData.version);
      formDataToSend.append("description", formData.description);
      formDataToSend.append("environment", formData.recommendedEnvironment);

      if (componentType === "vc_model") {
        formDataToSend.append("modelType", formData.modelType);
      }

      // features 추가 (한 블록으로 전송)
      formDataToSend.append("features", formData.mainFeatures);

      if (submittedFiles.thumbnail) {
        formDataToSend.append("thumbnail", submittedFiles.thumbnail);
        console.log("썸네일 FormData에 추가됨");
      }

      // 소스 파일 처리
      if (useExistingSource && existingFiles.source) {
        // 기존 소스 파일 사용 시 경로 전송
        formDataToSend.append("useExistingSource", "true");
        formDataToSend.append("existingSourcePath", existingFiles.source);
      } else if (submittedFiles.source) {
        // 새 소스 파일 선택 시
        formDataToSend.append("sourceFile", submittedFiles.source);
      }

      // 아이콘 파일 처리
      if (useExistingIcon && existingFiles.icon) {
        // 기존 Icon 파일 사용 시 경로 전송
        formDataToSend.append("useExistingIcon", "true");
        formDataToSend.append("existingIconPath", existingFiles.icon);
      } else if (submittedFiles.icon) {
        // 새 Icon 파일 선택 시
        formDataToSend.append("iconFile", submittedFiles.icon);
      }

      // FBX 파일 처리 (VC Model)
      if (useExistingFbx && existingFiles.fbx) {
        formDataToSend.append("useExistingFbx", "true");
        formDataToSend.append("existingFbxPath", existingFiles.fbx);
      } else if (submittedFiles.fbx) {
        formDataToSend.append("fbxFile", submittedFiles.fbx);
      }

      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/components/${componentId}`,
        {
          method: "PATCH",
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
          body: formDataToSend,
        }
      );

      if (response.status === 401) {
        showAlert("인증이 만료되었습니다. 다시 로그인해주세요.", { title: "인증 오류", type: "error" });
        return;
      }

      const data = await response.json();

      if (data.success) {
        showToast("버전이 업데이트되었습니다.", "success");
        handleClose();

        // 최신 버전 페이지로 리다이렉션
        if (data.data?.latestVersion?.id) {
          router.push(`/manage/${data.data.latestVersion.id}`);
        } else if (onSuccess) {
          onSuccess();
        }
      } else {
        showAlert(data.message || "버전 업데이트에 실패했습니다.", { title: "업데이트 실패", type: "error" });
      }
    } catch (error) {
      console.error("버전 업데이트 중 오류 발생:", error);
      showAlert("버전 업데이트 중 오류가 발생했습니다.", { title: "오류 발생", type: "error" });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const accessToken = getAccessToken();
    const { showAlert } = useAlertStore.getState();

    if (!accessToken) {
      showAlert("로그인이 필요한 서비스입니다.", { title: "접근 제한", type: "warning" });
      return;
    }

    if (!files.source && !useExistingSource) {
      showAlert("소스/실행 파일은 필수입니다.", { title: "필수 입력 누락", type: "warning" });
      return;
    }

    const finalFiles = { ...files };

    const isFbxActive = files.fbx || (useExistingFbx && existingFiles.fbx);
    if (!finalFiles.thumbnail && !thumbnailPreview && !autoGeneratedThumbnail && isFbxActive && fbxGenRef.current) {
        try {
            const dataUrl = await fbxGenRef.current.generateThumbnail();
            if (dataUrl && typeof dataUrl === 'string') {
                const arr = dataUrl.split(',');
                const mimeMatch = arr[0].match(/:(.*?);/);
                if (mimeMatch) {
                    const mime = mimeMatch[1];
                    const bstr = atob(arr[1]);
                    let n = bstr.length;
                    const u8arr = new Uint8Array(n);
                    while (n--) {
                        u8arr[n] = bstr.charCodeAt(n);
                    }
                    const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                    finalFiles.thumbnail = file;
                }
            }
        } catch (error) {
            console.error("자동 캡처 실패:", error);
        }
    }

    try {
      setIsSubmitting(true);
      await onSubmit(finalFiles);
    } catch (err) {
      console.error("업데이트 제출 에러:", err);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-gray-800 rounded-2xl p-6 w-[600px] max-h-[85vh] overflow-y-auto relative shadow-2xl">
        {/* 업로드 중 로딩 오버레이 */}
        {isSubmitting && (
          <div className="absolute inset-0 bg-black/80 backdrop-blur-md rounded-2xl flex flex-col items-center justify-center z-50 p-6 text-center">
            <div className="w-14 h-14 border-4 border-cyan-500 border-t-transparent rounded-full animate-spin mb-4 shadow-[0_0_20px_rgba(6,182,212,0.6)]" />
            <h4 className="text-white font-bold text-lg mb-2">버전 정보를 서버로 업로드하는 중입니다...</h4>
            <p className="text-cyan-200 text-xs leading-relaxed max-w-sm">
              대용량 파일 전송 시 수 초 정도 소요될 수 있습니다.<br />
              업로드가 완료될 때까지 창을 닫거나 새로고침하지 마세요.
            </p>
          </div>
        )}

        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-bold text-white">새 버전 등록</h2>
          <button
            onClick={handleClose}
            disabled={isSubmitting}
            className="text-gray-400 hover:text-white transition-colors disabled:opacity-50"
          >
            ✕
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              버전
            </label>
            <input
              type="text"
              value={formData.version}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, version: e.target.value }))
              }
              className="w-full px-3 py-2 bg-gray-700 rounded-md text-white"
              placeholder="예: 1.0.0"
            />
          </div>


          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              주요 기능(줄바꿈으로 구분)
            </label>
            <textarea
              value={formData.mainFeatures}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  mainFeatures: e.target.value,
                }))
              }
              className="w-full px-3 py-2 bg-gray-700 rounded-md text-white h-24 resize-none"
              placeholder="주요 기능을 입력하세요"
            />
          </div>


          {/* 기존 썸네일 미리보기 섹션 - 기존 소스 파일 사용 시 */}
          {useExistingSource && !files.fbx && initialData?.thumbnailImage && (
            <div className="mb-6 bg-gray-800 rounded-lg p-4">
              <h3 className="text-white font-semibold mb-4 flex items-center">
                기존 썸네일 미리보기
              </h3>

              <div className="flex items-center justify-center">
                <div className="relative w-64 h-64 bg-gray-700 rounded-lg overflow-hidden border border-gray-600">
                  {!isPlaceholderThumbnail(initialData.thumbnailImage) ? (
                    isVideoThumbnail(initialData.thumbnailImage) ? (
                      <VideoThumbnail
                        src={
                          initialData.thumbnailImage.startsWith("http")
                            ? initialData.thumbnailImage
                            : `${process.env.NEXT_PUBLIC_API_URL}${initialData.thumbnailImage}`
                        }
                        alt="기존 썸네일"
                      />
                    ) : (
                      <Image
                        src={
                          initialData.thumbnailImage.startsWith("http")
                            ? initialData.thumbnailImage
                            : `${process.env.NEXT_PUBLIC_API_URL}${initialData.thumbnailImage}`
                        }
                        alt="기존 썸네일"
                        fill
                        className="object-cover"
                        unoptimized
                      />
                    )
                  ) : (
                    <ThumbnailPlaceholder type={componentType} name={formData.componentName} />
                  )}
                </div>
              </div>

              <p className="text-gray-400 text-sm mt-2 text-center">
                💡 기존 파일을 사용하므로 기존 썸네일이 유지됩니다.
              </p>
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                컴포넌트 이름 (필수)
              </label>
              <input
                type="text"
                value={formData.componentName}
                onChange={(e) =>
                  setFormData({ ...formData, componentName: e.target.value })
                }
                className="w-full px-3 py-2 bg-gray-700 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="컴포넌트 이름을 입력하세요"
              />
            </div>

            <div className="flex gap-4">
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  버전 (필수)
                </label>
                <input
                  type="text"
                  value={formData.version}
                  onChange={(e) =>
                    setFormData({ ...formData, version: e.target.value })
                  }
                  className="w-full px-3 py-2 bg-gray-700 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="예: 1.0.1"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                {componentType === "vc_model" ? "VCMX 파일 (필수)" : componentType === "vc_plugin" ? "설치파일 (필수)" : "파일 (필수, 모든 확장자)"}
              </label>
              {existingFiles.source && (
                <>
                  <div className="mb-2 text-sm text-gray-400">
                    현재 파일: {existingFiles.source.split("/").pop()}
                  </div>
                  <div className="mb-2">
                    <label className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        checked={useExistingSource}
                        onChange={(e) => {
                          setUseExistingSource(e.target.checked);
                          if (e.target.checked) {
                            // 체크박스가 체크되면 선택된 파일 제거
                            setFiles((prev) => ({ ...prev, source: undefined }));
                            // 파일 선택창 초기화
                            if (sourceFileInputRef.current) {
                              sourceFileInputRef.current.value = "";
                            }
                            // 기존 썸네일 미리보기 복원
                            if (initialData?.thumbnailImage && !isPlaceholderThumbnail(initialData.thumbnailImage)) {
                              const thumbnailUrl =
                                initialData.thumbnailImage.startsWith("http")
                                  ? initialData.thumbnailImage
                                  : `${process.env.NEXT_PUBLIC_API_URL}${initialData.thumbnailImage}`;
                              setThumbnailPreview(thumbnailUrl);
                            } else {
                              setThumbnailPreview(null);
                            }
                          }
                        }}
                        className="w-4 h-4 text-blue-600 bg-gray-700 border-gray-600 rounded focus:ring-blue-500 focus:ring-2"
                      />
                      <span className="text-sm text-gray-300">
                        기존 파일 사용
                      </span>
                    </label>
                  </div>
                </>
              )}
              <input
                ref={sourceFileInputRef}
                type="file"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) {
                    const ext = file.name.split('.').pop()?.toLowerCase();
                    if (componentType === "vc_model" && ext !== "vcmx") {
                      useAlertStore.getState().showAlert("VC Model의 소스 파일은 .vcmx 확장자만 가능합니다.", { title: "형식 오류", type: "warning" });
                      e.target.value = "";
                      return;
                    }
                    
                    setFiles((prev) => ({ ...prev, source: file }));
                    setUseExistingSource(false);
                    // 새 소스 선택 시에도 사용자가 썸네일을 따로 올리지 않으면 기존 썸네일 유지
                    setAutoGeneratedThumbnail(null);
                  }
                }}
                className="w-full px-3 py-2 bg-gray-700 rounded-md text-white"
              />
            </div>

            {/* 썸네일 설정 섹션 (NS/etc Model은 제외) */}
            {componentType !== "ns_model" && componentType !== "etc" && (
              <div className="mb-6 bg-gray-800 rounded-lg p-4 mt-4">
                <h3 className="text-white font-semibold mb-4 flex items-center justify-between">
                  <span>썸네일 설정</span>
                  {componentType === "vc_plugin" && (
                    <span className="bg-red-500/20 border border-red-500/60 text-red-400 text-xs px-3 py-1 rounded-full font-bold animate-pulse">
                      동영상 썸네일 필수 (MP4 / WebM)
                    </span>
                  )}
                </h3>

                {componentType === "vc_plugin" && (
                  <div className="mb-5 p-4 bg-cyan-950/90 border-2 border-cyan-400 rounded-xl flex items-start gap-3 shadow-[0_0_20px_rgba(6,182,212,0.25)]">
                    <div className="text-xs leading-relaxed">
                      <div className="font-bold text-cyan-300 text-sm flex items-center gap-2 mb-1">
                        <span>[필수] VC PlugIn 동영상 썸네일 안내</span>
                        <span className="bg-cyan-400 text-black px-1.5 py-0.5 rounded text-[10px] font-extrabold uppercase">Required</span>
                      </div>
                      <p className="text-cyan-100/90">
                        VC PlugIn 업데이트 시에는 <strong className="text-white underline underline-offset-2 decoration-cyan-400 font-bold">MP4 또는 WebM 동영상 썸네일</strong>을 업로드하셔야 정상 반영됩니다. (새 썸네일을 올리지 않으면 기존 동영상 썸네일이 유지됩니다)
                      </p>
                    </div>
                  </div>
                )}

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {/* 썸네일 결과 (또는 기본 아이콘 / 3D 뷰어) */}
                  <div className="flex flex-col items-center justify-center bg-gray-800/50 rounded-xl border border-gray-700 p-2">
                    <div className="relative w-full aspect-square max-w-[300px] bg-gray-900 rounded-2xl flex flex-col items-center justify-center border border-gray-600 overflow-hidden shadow-inner">
                      {thumbnailPreview ? (
                        <>
                          {isVideoThumbnail(thumbnailPreview) || (files.thumbnail && isSupportedVideoFile(files.thumbnail)) ? (
                            <VideoThumbnail
                              src={thumbnailPreview}
                              alt="썸네일"
                            />
                          ) : (
                            <Image
                              src={thumbnailPreview}
                              alt="썸네일"
                              fill
                              className="object-cover"
                              unoptimized
                            />
                          )}
                          <button
                            type="button"
                            onClick={() => {
                              if (thumbnailPreview?.startsWith("blob:")) {
                                URL.revokeObjectURL(thumbnailPreview);
                              }
                              setThumbnailPreview("");
                              setFiles((prev) => ({
                                ...prev,
                                thumbnail: undefined,
                              }));
                            }}
                            className="absolute top-2 right-2 bg-red-500/80 text-white rounded-full w-7 h-7 flex items-center justify-center hover:bg-red-500 transition-colors shadow-lg backdrop-blur-sm z-30"
                          >
                            ✕
                          </button>
                        </>
                      ) : (files.fbx || (useExistingFbx && existingFiles.fbx)) ? (
                        <div className="w-full h-full relative">
                          <FbxThumbnailGenerator
                            ref={fbxGenRef}
                            fbxFile={files.fbx}
                            fbxUrl={useExistingFbx && existingFiles.fbx ? `${process.env.NEXT_PUBLIC_API_URL}${existingFiles.fbx}` : null}
                            onThumbnailGenerated={(dataUrl: string) => {
                              setAutoGeneratedThumbnail(dataUrl);
                            }}
                          />
                          {autoGeneratedThumbnail && (
                            <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center z-10 p-2">
                              <div className="relative w-full h-full">
                               <Image 
                                 src={autoGeneratedThumbnail} 
                                 fill
                                 className="object-cover border-2 border-cyan-500 rounded-lg" 
                                 alt="생성된 썸네일"
                                 unoptimized
                               />
                              </div>
                               <button
                                 type="button"
                                 onClick={() => {
                                   setAutoGeneratedThumbnail(null);
                                   setFiles(prev => ({ ...prev, thumbnail: undefined }));
                                 }}
                                 className="absolute bottom-2 left-1/2 -translate-x-1/2 bg-red-500/90 text-white rounded-full px-3 py-1 text-xs hover:bg-red-500 transition-colors shadow-lg whitespace-nowrap"
                               >
                                 ✕ 다시 촬영
                               </button>
                            </div>
                          )}
                          {!autoGeneratedThumbnail && (
                            <div className="absolute bottom-2 right-2 z-20">
                              <button
                                type="button"
                                onClick={async () => {
                                  if (fbxGenRef.current) {
                                    const dataUrl = await fbxGenRef.current.generateThumbnail();
                                    if (dataUrl) {
                                      setAutoGeneratedThumbnail(dataUrl);
                                      const arr = dataUrl.split(',');
                                      const mime = arr[0].match(/:(.*?);/)?.[1];
                                      const bstr = atob(arr[1]);
                                      let n = bstr.length;
                                      const u8arr = new Uint8Array(n);
                                      while (n--) {
                                        u8arr[n] = bstr.charCodeAt(n);
                                      }
                                      const file = new File([u8arr], `thumbnail_${Date.now()}.png`, { type: mime });
                                      setFiles(prev => ({ ...prev, thumbnail: file }));
                                    }
                                  }
                                }}
                                className="bg-cyan-600 hover:bg-cyan-500 text-white text-[10px] px-2 py-1 rounded shadow-lg border border-cyan-400/50 flex items-center gap-1 transition-all active:scale-95"
                              >
                                📸 캡처
                              </button>
                            </div>
                          )}
                        </div>
                      ) : (
                        <div className="w-full h-full relative">
                          <ThumbnailPlaceholder type={componentType} name={initialData?.version} />
                        </div>
                      )}
                    </div>
                  </div>

                  {/* 오른쪽: 직접 썸네일 업로드 섹션 */}
                  <div className="flex flex-col justify-center">
                    <h4 className="text-white font-medium mb-2 text-base flex items-center gap-2">
                      <span>직접 썸네일 설정</span>
                      {componentType === "vc_plugin" ? (
                        <span className="text-red-400 text-xs font-bold bg-red-950/80 border border-red-500/50 px-2 py-0.5 rounded">
                          동영상 (MP4 / WebM)
                        </span>
                      ) : (
                        <span className="text-gray-400 text-xs font-normal ml-1">(선택항목)</span>
                      )}
                    </h4>
                    <p className="text-gray-400 text-xs mb-4 leading-relaxed">
                      {componentType === "vc_plugin"
                        ? "새 동영상 썸네일을 업로드하려면 MP4 또는 WebM 파일을 선택하세요. (미선택 시 기존 썸네일 유지)"
                        : `직접 이미지를 업로드하지 않으면 상단의 ${(files.fbx || (useExistingFbx && existingFiles.fbx)) ? '캡처본' : '기본 아이콘'}이 썸네일로 사용됩니다.`}
                    </p>
                    
                    <div className="relative">
                      <input
                        type="file"
                        id="update-thumbnail-upload-new"
                        name="thumbnail"
                        accept={componentType === "vc_plugin" ? "video/mp4,video/webm" : "image/*"}
                        onChange={handleThumbnailChange}
                        className="hidden"
                      />
                      <label 
                        htmlFor="update-thumbnail-upload-new"
                        className={`w-full cursor-pointer p-3 rounded-lg border transition-all text-xs flex items-center justify-between group ${
                          componentType === "vc_plugin" && !files.thumbnail
                            ? "bg-cyan-950/40 border-cyan-500/80 hover:bg-cyan-900/50 text-cyan-200"
                            : "bg-gray-900 hover:bg-gray-750 text-gray-300 border-gray-700/50"
                        }`}
                      >
                        <span className="truncate">{files.thumbnail ? files.thumbnail.name : (componentType === "vc_plugin" ? '동영상 파일 선택 (MP4, WebM)' : '파일을 선택하세요')}</span>
                        <span className="bg-cyan-600 group-hover:bg-cyan-500 px-2 py-1 rounded text-[10px] text-white shrink-0 ml-2 font-medium">파일 찾기</span>
                      </label>
                    </div>
                    <p className="text-gray-500 text-[10px] mt-2">
                      {componentType === "vc_plugin" ? "💡 MP4, WebM 동영상 권장" : "💡 1:1 비율 권장"}
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* 모델 타입 (VC Model 전용) */}
            {componentType === "vc_model" && (
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  모델 타입
                </label>
                <select
                  value={formData.modelType}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, modelType: e.target.value }))
                  }
                  className="w-full px-3 py-2 bg-gray-700 rounded-md text-white border border-gray-600 focus:border-cyan-500 outline-none transition-all"
                >
                  <option value="component">컴포넌트</option>
                  <option value="layout">레이아웃</option>
                </select>
              </div>
            )}

            {/* FBX 파일 (VC Model 전용) */}
            {componentType === "vc_model" && (
              <div className="bg-gray-800/50 rounded-lg p-4 border border-gray-700">
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  FBX 파일 (선택)
                </label>
                {existingFiles.fbx && (
                  <>
                    <div className="mb-2 text-sm text-gray-400">
                      현재 파일: {existingFiles.fbx.split("/").pop()}
                    </div>
                    <div className="mb-2">
                      <label className="flex items-center space-x-2 cursor-pointer group">
                        <input
                          type="checkbox"
                          checked={useExistingFbx}
                          onChange={(e) => {
                            setUseExistingFbx(e.target.checked);
                            if (e.target.checked) {
                              setFiles((prev) => ({ ...prev, fbx: undefined }));
                            }
                          }}
                          className="w-4 h-4 text-cyan-600 bg-gray-700 border-gray-600 rounded focus:ring-cyan-500 focus:ring-2"
                        />
                        <span className="text-sm text-gray-300 group-hover:text-white transition-colors">
                          기존 FBX 파일 사용
                        </span>
                      </label>
                    </div>
                  </>
                )}
                <input
                  type="file"
                  accept=".fbx"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                      const ext = file.name.split('.').pop()?.toLowerCase();
                      if (ext !== "fbx") {
                        useAlertStore.getState().showAlert("FBX 파일은 .fbx 확장자만 가능합니다.", { title: "형식 오류", type: "warning" });
                        e.target.value = "";
                        return;
                      }

                      setFiles((prev) => ({ ...prev, fbx: file }));
                      setUseExistingFbx(false);
                      setThumbnailPreview("");
                      setAutoGeneratedThumbnail(null);
                    }
                  }}
                  className="w-full px-3 py-2 bg-gray-700 rounded-md text-white border border-gray-600 focus:border-cyan-500 outline-none transition-all"
                />
                <p className="text-xs text-gray-400 mt-2">
                  💡 FBX 파일을 업로드하면 3D 뷰어 기능이 활성화됩니다.
                </p>
              </div>
            )}
          </div>

          <div className="flex justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={handleClose}
              disabled={isSubmitting}
              className="px-6 py-2.5 rounded-lg border border-gray-600/50 bg-gray-800/50 text-gray-300 hover:bg-gray-700 hover:text-white transition-all font-medium backdrop-blur-sm disabled:opacity-50"
            >
              취소
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="px-6 py-2.5 rounded-lg bg-cyan-600/90 hover:bg-cyan-500 border border-cyan-400/50 text-white font-medium shadow-[0_0_15px_rgba(8,145,178,0.3)] transition-all disabled:opacity-50 flex items-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>업로드 중...</span>
                </>
              ) : (
                "등록"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default VersionUpdateModal;
